'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4984
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebElement.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DownloadDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownloadDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property errorDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("errorDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HorizontalBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalBottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HorizontalLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HorizontalRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HorizontalTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ImageDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ImageDefault2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDefault2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ImageRssDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageRssDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property luggerbu() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("luggerbu", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property MenuSeparator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSeparator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuSubIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSubIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RadioDispositionSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RadioDispositionSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VerticalJustifyLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalJustifyLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VerticalJustifyRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalJustifyRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VerticalLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VerticalRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEAlertBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEAlertBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEBreadCrumbs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEBreadCrumbs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECadre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECadre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECaptcha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECaptcha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECarrousel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECarrousel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECarrousel2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECarrousel2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECheckbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECheckbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECodeBlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECodeBlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECollapsiblePanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECollapsiblePanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WECounter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WECounter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEDocument() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEDocument", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEDownloadFiles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEDownloadFiles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEFlag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEFlag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEFlash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEFlash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEGallery1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEGallery1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEGPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEGPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEHelpUs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEHelpUs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEHr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEHr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEHrVertival() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEHrVertival", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WELabel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELabel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WELink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WELinkButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELinkButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WELinkImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELinkImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEListBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEListBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEMenuAccordion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEMenuAccordion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEPanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEPanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEPayPal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEPayPal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WERadioButtonList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WERadioButtonList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WERssWriter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WERssWriter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEScriptHidden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEScriptHidden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WESendForm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WESendForm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WESendMail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WESendMail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WESlideshow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WESlideshow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WETable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WETable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WETextArea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WETextArea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WETextBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WETextBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WETreeView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WETreeView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEUploadFiles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEUploadFiles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEVideo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEVideo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEW3C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEW3C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
