'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4984
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources.text
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizablePropertyDefaultValue
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebElement.LocalizablePropertyDefaultValue", GetType(LocalizablePropertyDefaultValue).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mon texte multi-lignes.
        '''</summary>
        Friend Shared ReadOnly Property _0001() As String
            Get
                Return ResourceManager.GetString("_0001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mon texte simple.
        '''</summary>
        Friend Shared ReadOnly Property _0002() As String
            Get
                Return ResourceManager.GetString("_0002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Site créé avec openElement.
        '''</summary>
        Friend Shared ReadOnly Property _0003() As String
            Get
                Return ResourceManager.GetString("_0003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte associé au fichier à télécharger.
        '''</summary>
        Friend Shared ReadOnly Property _0004() As String
            Get
                Return ResourceManager.GetString("_0004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nouveau lien.
        '''</summary>
        Friend Shared ReadOnly Property _0005() As String
            Get
                Return ResourceManager.GetString("_0005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mon message ....
        '''</summary>
        Friend Shared ReadOnly Property _0006() As String
            Get
                Return ResourceManager.GetString("_0006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du champ :.
        '''</summary>
        Friend Shared ReadOnly Property _0007() As String
            Get
                Return ResourceManager.GetString("_0007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte du champ.
        '''</summary>
        Friend Shared ReadOnly Property _0008() As String
            Get
                Return ResourceManager.GetString("_0008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur du champ.
        '''</summary>
        Friend Shared ReadOnly Property _0009() As String
            Get
                Return ResourceManager.GetString("_0009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mon bouton.
        '''</summary>
        Friend Shared ReadOnly Property _0010() As String
            Get
                Return ResourceManager.GetString("_0010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le message a été envoyé..
        '''</summary>
        Friend Shared ReadOnly Property _0011() As String
            Get
                Return ResourceManager.GetString("_0011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une erreur s&apos;est produite pendant l&apos;envoi, le message n&apos;a pas été envoyé..
        '''</summary>
        Friend Shared ReadOnly Property _0012() As String
            Get
                Return ResourceManager.GetString("_0012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;affichage en prévisualisation de la galerie ne prend pas en compte le redimensionnement réel des images.&lt;br /&gt; Il n&apos;est pris en compte que pour l&apos;affichage en ligne..
        '''</summary>
        Friend Shared ReadOnly Property _0013() As String
            Get
                Return ResourceManager.GetString("_0013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du champ.
        '''</summary>
        Friend Shared ReadOnly Property _0014() As String
            Get
                Return ResourceManager.GetString("_0014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;affichage des images du carrousel est provisoirement désactivé dans le mode éditeur. Le résultat final reste visible en mode prévisualisation.
        '''</summary>
        Friend Shared ReadOnly Property _0015() As String
            Get
                Return ResourceManager.GetString("_0015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En ligne uniquement.
        '''</summary>
        Friend Shared ReadOnly Property _0016() As String
            Get
                Return ResourceManager.GetString("_0016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Clic droit interdit.
        '''</summary>
        Friend Shared ReadOnly Property _0017() As String
            Get
                Return ResourceManager.GetString("_0017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien n°{0} du menu.
        '''</summary>
        Friend Shared ReadOnly Property _0018() As String
            Get
                Return ResourceManager.GetString("_0018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre du groupe.
        '''</summary>
        Friend Shared ReadOnly Property _0019() As String
            Get
                Return ResourceManager.GetString("_0019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Description du groupe.
        '''</summary>
        Friend Shared ReadOnly Property _0020() As String
            Get
                Return ResourceManager.GetString("_0020", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
