'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4984
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources.text
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizablePropertyDescription
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebElement.LocalizablePropertyDescription", GetType(LocalizablePropertyDescription).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration du compteur..
        '''</summary>
        Friend Shared ReadOnly Property _D001() As String
            Get
                Return ResourceManager.GetString("_D001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de l&apos;image principale de l&apos;élément..
        '''</summary>
        Friend Shared ReadOnly Property _D002() As String
            Get
                Return ResourceManager.GetString("_D002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection du lien principal de l&apos;élément..
        '''</summary>
        Friend Shared ReadOnly Property _D003() As String
            Get
                Return ResourceManager.GetString("_D003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Description de l&apos;image..
        '''</summary>
        Friend Shared ReadOnly Property _D004() As String
            Get
                Return ResourceManager.GetString("_D004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Epaisseur du trait..
        '''</summary>
        Friend Shared ReadOnly Property _D005() As String
            Get
                Return ResourceManager.GetString("_D005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur du trait..
        '''</summary>
        Friend Shared ReadOnly Property _D006() As String
            Get
                Return ResourceManager.GetString("_D006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte affiché..
        '''</summary>
        Friend Shared ReadOnly Property _D007() As String
            Get
                Return ResourceManager.GetString("_D007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de l&apos;image principale associée au lien..
        '''</summary>
        Friend Shared ReadOnly Property _D008() As String
            Get
                Return ResourceManager.GetString("_D008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection du fichier à télécharger..
        '''</summary>
        Friend Shared ReadOnly Property _D009() As String
            Get
                Return ResourceManager.GetString("_D009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de la fenêtre de destination du lien principal de l&apos;élément..
        '''</summary>
        Friend Shared ReadOnly Property _D010() As String
            Get
                Return ResourceManager.GetString("_D010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration du menu..
        '''</summary>
        Friend Shared ReadOnly Property _D011() As String
            Get
                Return ResourceManager.GetString("_D011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de l&apos;icône indiquant un sous-menu..
        '''</summary>
        Friend Shared ReadOnly Property _D012() As String
            Get
                Return ResourceManager.GetString("_D012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du menu principal sur le déclencheur..
        '''</summary>
        Friend Shared ReadOnly Property _D013() As String
            Get
                Return ResourceManager.GetString("_D013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Décalage horizontal de la position du menu principal sur le déclencheur (en pixels). Les valeurs négatives sont autorisées..
        '''</summary>
        Friend Shared ReadOnly Property _D014() As String
            Get
                Return ResourceManager.GetString("_D014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Décalage vertical de la position du menu principal sur le déclencheur (en pixels). Les valeurs négatives sont autorisées..
        '''</summary>
        Friend Shared ReadOnly Property _D015() As String
            Get
                Return ResourceManager.GetString("_D015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse de l&apos;animation à l&apos;ouverture des sous-menus..
        '''</summary>
        Friend Shared ReadOnly Property _D016() As String
            Get
                Return ResourceManager.GetString("_D016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse de l&apos;animation à la fermeture des sous-menus..
        '''</summary>
        Friend Shared ReadOnly Property _D017() As String
            Get
                Return ResourceManager.GetString("_D017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai minimum de fermeture du menu après sélection..
        '''</summary>
        Friend Shared ReadOnly Property _D018() As String
            Get
                Return ResourceManager.GetString("_D018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à URL de la vidéo YouTube..
        '''</summary>
        Friend Shared ReadOnly Property _D019() As String
            Get
                Return ResourceManager.GetString("_D019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur claire du lecteur et de la bordure..
        '''</summary>
        Friend Shared ReadOnly Property _D020() As String
            Get
                Return ResourceManager.GetString("_D020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur foncée du lecteur et de la bordure..
        '''</summary>
        Friend Shared ReadOnly Property _D021() As String
            Get
                Return ResourceManager.GetString("_D021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage de la bordure..
        '''</summary>
        Friend Shared ReadOnly Property _D022() As String
            Get
                Return ResourceManager.GetString("_D022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection du fichier vidéo.
        '''Seules les extensions suivantes sont acceptées : .agi, .grimpe, .mpg, .au, .aif, .mp3, .mp2, .mp1, .mpe, .mpga, .ra, .ram, .rm, .rmj, .rms, .mmd..
        '''</summary>
        Friend Shared ReadOnly Property _D023() As String
            Get
                Return ResourceManager.GetString("_D023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage automatique de la vidéo au chargement de la page..
        '''</summary>
        Friend Shared ReadOnly Property _D024() As String
            Get
                Return ResourceManager.GetString("_D024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage des contrôles et/ou de la fenêtre de la vidéo.
        '''Ne s&apos;affiche que si l&apos;élément est d&apos;une taille supérieure à la vidéo..
        '''</summary>
        Friend Shared ReadOnly Property _D025() As String
            Get
                Return ResourceManager.GetString("_D025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répétition en boucle de la vidéo..
        '''</summary>
        Friend Shared ReadOnly Property _D026() As String
            Get
                Return ResourceManager.GetString("_D026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage de la vidéo en conservant la proportion hauteur/largeur..
        '''</summary>
        Friend Shared ReadOnly Property _D027() As String
            Get
                Return ResourceManager.GetString("_D027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur de fond du lecteur..
        '''</summary>
        Friend Shared ReadOnly Property _D028() As String
            Get
                Return ResourceManager.GetString("_D028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection du fichier vidéo.
        '''Seules les extensions suivantes sont acceptées : .avi, .mov, .mpeg, .mpg, .wav, .mp3, .mp2..
        '''</summary>
        Friend Shared ReadOnly Property _D029() As String
            Get
                Return ResourceManager.GetString("_D029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage des contrôles de la vidéo.
        '''Ne s&apos;affiche que si l&apos;élément est d&apos;une taille supérieure à la vidéo..
        '''</summary>
        Friend Shared ReadOnly Property _D030() As String
            Get
                Return ResourceManager.GetString("_D030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection du fichier vidéo.
        '''Seules les extensions suivantes sont acceptées : .avi, .wme, .wma, .wmv, .mpeg, .ogg, .ogm, .mp3, .wav, .midi, .mdi, .snd, .ai, .aif, .aifc, .aiff, .rmi, .mpg, .mdv, .mp2, .mpe, .asf, .wm..
        '''</summary>
        Friend Shared ReadOnly Property _D031() As String
            Get
                Return ResourceManager.GetString("_D031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à URL de la vidéo Dailymotion..
        '''</summary>
        Friend Shared ReadOnly Property _D032() As String
            Get
                Return ResourceManager.GetString("_D032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection du fichier flash..
        '''</summary>
        Friend Shared ReadOnly Property _D033() As String
            Get
                Return ResourceManager.GetString("_D033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage automatique de l&apos;animation au chargement de la page..
        '''</summary>
        Friend Shared ReadOnly Property _D034() As String
            Get
                Return ResourceManager.GetString("_D034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répétition en boucle du flash..
        '''</summary>
        Friend Shared ReadOnly Property _D035() As String
            Get
                Return ResourceManager.GetString("_D035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Afficher le menu complet du flash..
        '''</summary>
        Friend Shared ReadOnly Property _D036() As String
            Get
                Return ResourceManager.GetString("_D036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Qualité de l&apos;animation flash..
        '''</summary>
        Friend Shared ReadOnly Property _D037() As String
            Get
                Return ResourceManager.GetString("_D037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Définit l&apos;alignement du flash dans la fenêtre..
        '''</summary>
        Friend Shared ReadOnly Property _D038() As String
            Get
                Return ResourceManager.GetString("_D038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Définit l&apos;endroit de l&apos;alignement du flash à l&apos;intérieur de la zone d&apos;encadrement..
        '''</summary>
        Friend Shared ReadOnly Property _D039() As String
            Get
                Return ResourceManager.GetString("_D039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Définit le comportement du fond du flash par rapport au reste du contenu de la page..
        '''</summary>
        Friend Shared ReadOnly Property _D040() As String
            Get
                Return ResourceManager.GetString("_D040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur de fond du flash..
        '''</summary>
        Friend Shared ReadOnly Property _D041() As String
            Get
                Return ResourceManager.GetString("_D041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Méthode de recadrage du flash dans la fenêtre..
        '''</summary>
        Friend Shared ReadOnly Property _D042() As String
            Get
                Return ResourceManager.GetString("_D042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition du texte du message d&apos;alerte..
        '''</summary>
        Friend Shared ReadOnly Property _D043() As String
            Get
                Return ResourceManager.GetString("_D043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Désactiver le message pendant l&apos;édition de la page..
        '''</summary>
        Friend Shared ReadOnly Property _D044() As String
            Get
                Return ResourceManager.GetString("_D044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du titre par rapport à l&apos;élément de téléchargement..
        '''</summary>
        Friend Shared ReadOnly Property _D045() As String
            Get
                Return ResourceManager.GetString("_D045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste des extensions autorisées (ex : .jpg,.png) des fichiers à importer..
        '''</summary>
        Friend Shared ReadOnly Property _D046() As String
            Get
                Return ResourceManager.GetString("_D046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille maximum autorisée des fichiers à importer..
        '''</summary>
        Friend Shared ReadOnly Property _D047() As String
            Get
                Return ResourceManager.GetString("_D047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Largeur du champ texte associé au champ de téléchargement..
        '''</summary>
        Friend Shared ReadOnly Property _D048() As String
            Get
                Return ResourceManager.GetString("_D048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de l&apos;image principale de l&apos;élément situé à gauche du champ de téléchargement..
        '''</summary>
        Friend Shared ReadOnly Property _D049() As String
            Get
                Return ResourceManager.GetString("_D049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position de l&apos;image à gauche du champ de téléchargement..
        '''</summary>
        Friend Shared ReadOnly Property _D050() As String
            Get
                Return ResourceManager.GetString("_D050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition des règles de validation des saisies de l&apos;élément de formulaire..
        '''</summary>
        Friend Shared ReadOnly Property _D051() As String
            Get
                Return ResourceManager.GetString("_D051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de l&apos;image à afficher en cas d&apos;erreur de validation..
        '''</summary>
        Friend Shared ReadOnly Property _D052() As String
            Get
                Return ResourceManager.GetString("_D052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du champ de texte par rapport à la boîte de saisie..
        '''</summary>
        Friend Shared ReadOnly Property _D053() As String
            Get
                Return ResourceManager.GetString("_D053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte pré-rempli dans la boîte de saisie..
        '''</summary>
        Friend Shared ReadOnly Property _D054() As String
            Get
                Return ResourceManager.GetString("_D054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Largeur du champ texte associé à la boîte de saisie..
        '''</summary>
        Friend Shared ReadOnly Property _D055() As String
            Get
                Return ResourceManager.GetString("_D055", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de caractères maximum (espace compris) autorisés lors de la saisie dans la zone de texte. 
        '''Renseigner 0 pour un nombre illimité de caractères..
        '''</summary>
        Friend Shared ReadOnly Property _D056() As String
            Get
                Return ResourceManager.GetString("_D056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Définit la boîte de saisie comme étant en lecture seule..
        '''</summary>
        Friend Shared ReadOnly Property _D057() As String
            Get
                Return ResourceManager.GetString("_D057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélection de l&apos;image principale de l&apos;élément située à gauche du titre..
        '''</summary>
        Friend Shared ReadOnly Property _D058() As String
            Get
                Return ResourceManager.GetString("_D058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position verticale de l&apos;image située à gauche du titre..
        '''</summary>
        Friend Shared ReadOnly Property _D059() As String
            Get
                Return ResourceManager.GetString("_D059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Largeur de la zone de saisie du texte..
        '''</summary>
        Friend Shared ReadOnly Property _D060() As String
            Get
                Return ResourceManager.GetString("_D060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Comportement de l&apos;ascenseur (scrollbar) vertical associé à la boîte de saisie..
        '''</summary>
        Friend Shared ReadOnly Property _D061() As String
            Get
                Return ResourceManager.GetString("_D061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de colonnes (caractères) maximales en largeur. Indépendant de la largeur de la boîte de saisie..
        '''</summary>
        Friend Shared ReadOnly Property _D062() As String
            Get
                Return ResourceManager.GetString("_D062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de lignes de la boîte de saisie..
        '''</summary>
        Friend Shared ReadOnly Property _D063() As String
            Get
                Return ResourceManager.GetString("_D063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du titre par rapport à la boîte de saisie..
        '''</summary>
        Friend Shared ReadOnly Property _D064() As String
            Get
                Return ResourceManager.GetString("_D064", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ensemble des éléments contenus dans la liste de choix..
        '''</summary>
        Friend Shared ReadOnly Property _D065() As String
            Get
                Return ResourceManager.GetString("_D065", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du titre par rapport à la liste de choix..
        '''</summary>
        Friend Shared ReadOnly Property _D066() As String
            Get
                Return ResourceManager.GetString("_D066", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Style général de l&apos;affichage de la liste de choix, c&apos;est-à-dire, la position du texte et la disposition des éléments..
        '''</summary>
        Friend Shared ReadOnly Property _D067() As String
            Get
                Return ResourceManager.GetString("_D067", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de lignes affichées de la liste déroulante..
        '''</summary>
        Friend Shared ReadOnly Property _D068() As String
            Get
                Return ResourceManager.GetString("_D068", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ensemble des éléments contenus dans la liste déroulante..
        '''</summary>
        Friend Shared ReadOnly Property _D069() As String
            Get
                Return ResourceManager.GetString("_D069", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Autoriser les choix multiples d&apos;éléments..
        '''</summary>
        Friend Shared ReadOnly Property _D070() As String
            Get
                Return ResourceManager.GetString("_D070", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Activer ou non la liste déroulante. Si non, la liste est grisée..
        '''</summary>
        Friend Shared ReadOnly Property _D071() As String
            Get
                Return ResourceManager.GetString("_D071", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom pris en compte pour la validation du formulaire..
        '''</summary>
        Friend Shared ReadOnly Property _D072() As String
            Get
                Return ResourceManager.GetString("_D072", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du titre par rapport à liste de valeur..
        '''</summary>
        Friend Shared ReadOnly Property _D073() As String
            Get
                Return ResourceManager.GetString("_D073", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte principal affiché sur le bouton..
        '''</summary>
        Friend Shared ReadOnly Property _D074() As String
            Get
                Return ResourceManager.GetString("_D074", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte envoyé à la validation du formulaire (peut être différent du texte affiché)..
        '''</summary>
        Friend Shared ReadOnly Property _D075() As String
            Get
                Return ResourceManager.GetString("_D075", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du titre par rapport à la case à cocher..
        '''</summary>
        Friend Shared ReadOnly Property _D076() As String
            Get
                Return ResourceManager.GetString("_D076", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Définit la case à cocher comme étant en lecture seule (aucun cochage/décochage possible)..
        '''</summary>
        Friend Shared ReadOnly Property _D077() As String
            Get
                Return ResourceManager.GetString("_D077", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Définit si la case est cochée au chargement de la page..
        '''</summary>
        Friend Shared ReadOnly Property _D078() As String
            Get
                Return ResourceManager.GetString("_D078", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration des liaisons d&apos;éléments du formulaire à associer à l&apos;envoi de l&apos;e-mail..
        '''</summary>
        Friend Shared ReadOnly Property _D079() As String
            Get
                Return ResourceManager.GetString("_D079", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Information de configuration (obligatoire) pour l&apos;envoi de l&apos;e-mail..
        '''</summary>
        Friend Shared ReadOnly Property _D080() As String
            Get
                Return ResourceManager.GetString("_D080", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration de l&apos;envoi d&apos;e-mail..
        '''</summary>
        Friend Shared ReadOnly Property _D081() As String
            Get
                Return ResourceManager.GetString("_D081", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage des drapeaux..
        '''</summary>
        Friend Shared ReadOnly Property _D082() As String
            Get
                Return ResourceManager.GetString("_D082", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration de la galerie..
        '''</summary>
        Friend Shared ReadOnly Property _D083() As String
            Get
                Return ResourceManager.GetString("_D083", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai entre chaque défilement d&apos;image..
        '''</summary>
        Friend Shared ReadOnly Property _D084() As String
            Get
                Return ResourceManager.GetString("_D084", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de vignettes affichées par page dans la prévisualisation..
        '''</summary>
        Friend Shared ReadOnly Property _D085() As String
            Get
                Return ResourceManager.GetString("_D085", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de pages maximum affichées dans la prévisualisation..
        '''</summary>
        Friend Shared ReadOnly Property _D086() As String
            Get
                Return ResourceManager.GetString("_D086", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte du bouton permettant de passer à l&apos;image suivante..
        '''</summary>
        Friend Shared ReadOnly Property _D087() As String
            Get
                Return ResourceManager.GetString("_D087", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte du bouton permettant de passer à l&apos;image précédente..
        '''</summary>
        Friend Shared ReadOnly Property _D088() As String
            Get
                Return ResourceManager.GetString("_D088", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte du bouton permettant de passer à la page suivante dans la prévisualisation..
        '''</summary>
        Friend Shared ReadOnly Property _D089() As String
            Get
                Return ResourceManager.GetString("_D089", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte du bouton permettant de passer à la page précédente dans la prévisualisation..
        '''</summary>
        Friend Shared ReadOnly Property _D090() As String
            Get
                Return ResourceManager.GetString("_D090", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage automatique du lecteur..
        '''</summary>
        Friend Shared ReadOnly Property _D091() As String
            Get
                Return ResourceManager.GetString("_D091", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte du bouton permettant de lancer le lecteur automatique..
        '''</summary>
        Friend Shared ReadOnly Property _D092() As String
            Get
                Return ResourceManager.GetString("_D092", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte du bouton permettant d&apos;arrêter le lecteur automatique..
        '''</summary>
        Friend Shared ReadOnly Property _D093() As String
            Get
                Return ResourceManager.GetString("_D093", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Restaurer l&apos;image par défaut..
        '''</summary>
        Friend Shared ReadOnly Property _D094() As String
            Get
                Return ResourceManager.GetString("_D094", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage des boutons de contrôle de la lecture automatique des images..
        '''</summary>
        Friend Shared ReadOnly Property _D095() As String
            Get
                Return ResourceManager.GetString("_D095", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage des boutons de navigation des images (suivante/précédente)..
        '''</summary>
        Friend Shared ReadOnly Property _D096() As String
            Get
                Return ResourceManager.GetString("_D096", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répertoire de base ou URL pour résoudre tous les chemins relatifs contenus dans le flash..
        '''</summary>
        Friend Shared ReadOnly Property _D097() As String
            Get
                Return ResourceManager.GetString("_D097", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hauteur de l&apos;en-tête..
        '''</summary>
        Friend Shared ReadOnly Property _D098() As String
            Get
                Return ResourceManager.GetString("_D098", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte à afficher..
        '''</summary>
        Friend Shared ReadOnly Property _D099() As String
            Get
                Return ResourceManager.GetString("_D099", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position de l&apos;image par rapport au texte..
        '''</summary>
        Friend Shared ReadOnly Property _D100() As String
            Get
                Return ResourceManager.GetString("_D100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ecart entre les sous-menus (en pixels). Les valeurs négatives sont autorisées..
        '''</summary>
        Friend Shared ReadOnly Property _D101() As String
            Get
                Return ResourceManager.GetString("_D101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position de l&apos;en-tête sur la page (haut ou bas)..
        '''</summary>
        Friend Shared ReadOnly Property _D102() As String
            Get
                Return ResourceManager.GetString("_D102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre principal du groupe d&apos;éléments..
        '''</summary>
        Friend Shared ReadOnly Property _D103() As String
            Get
                Return ResourceManager.GetString("_D103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Icône du groupe en position fermée..
        '''</summary>
        Friend Shared ReadOnly Property _D104() As String
            Get
                Return ResourceManager.GetString("_D104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Icône du groupe en position ouverte..
        '''</summary>
        Friend Shared ReadOnly Property _D105() As String
            Get
                Return ResourceManager.GetString("_D105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ligne de texte pour la description du groupe..
        '''</summary>
        Friend Shared ReadOnly Property _D107() As String
            Get
                Return ResourceManager.GetString("_D107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Créer un lien texte pour l&apos;ouverture..
        '''</summary>
        Friend Shared ReadOnly Property _D108() As String
            Get
                Return ResourceManager.GetString("_D108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Disposition (verticale, horizontale) de la liste de choix..
        '''</summary>
        Friend Shared ReadOnly Property _D112() As String
            Get
                Return ResourceManager.GetString("_D112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position du champ de texte par rapport au bouton..
        '''</summary>
        Friend Shared ReadOnly Property _D113() As String
            Get
                Return ResourceManager.GetString("_D113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Alignement du texte et des boutons de choix..
        '''</summary>
        Friend Shared ReadOnly Property _D114() As String
            Get
                Return ResourceManager.GetString("_D114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Editer le bloc de code..
        '''</summary>
        Friend Shared ReadOnly Property _D115() As String
            Get
                Return ResourceManager.GetString("_D115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choix des images à afficher..
        '''</summary>
        Friend Shared ReadOnly Property _D116() As String
            Get
                Return ResourceManager.GetString("_D116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sens de déplacement si le mode auto est activé..
        '''</summary>
        Friend Shared ReadOnly Property _D117() As String
            Get
                Return ResourceManager.GetString("_D117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre d&apos;images décalées à chaque mouvement. Ce nombre doit être supérieur ou égal à zéro..
        '''</summary>
        Friend Shared ReadOnly Property _D118() As String
            Get
                Return ResourceManager.GetString("_D118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attente en milliseconde entre deux mouvements d&apos;image. Valable uniquement si le mode auto est sélectionné..
        '''</summary>
        Friend Shared ReadOnly Property _D119() As String
            Get
                Return ResourceManager.GetString("_D119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Déplacement des images en mode automatique..
        '''</summary>
        Friend Shared ReadOnly Property _D120() As String
            Get
                Return ResourceManager.GetString("_D120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse de défilement en milliseconde. Temps utilisé pour déplacer une image. Le temps de déplacement global dépend donc de cette valeur et du décalage..
        '''</summary>
        Friend Shared ReadOnly Property _D121() As String
            Get
                Return ResourceManager.GetString("_D121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Editer le document.
        '''</summary>
        Friend Shared ReadOnly Property _D122() As String
            Get
                Return ResourceManager.GetString("_D122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image de fond du bouton normal..
        '''</summary>
        Friend Shared ReadOnly Property _D123() As String
            Get
                Return ResourceManager.GetString("_D123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image de fond du bouton au survol de la souris..
        '''</summary>
        Friend Shared ReadOnly Property _D124() As String
            Get
                Return ResourceManager.GetString("_D124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image de fond du bouton au clic de la souris..
        '''</summary>
        Friend Shared ReadOnly Property _D125() As String
            Get
                Return ResourceManager.GetString("_D125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Script javascript.
        '''</summary>
        Friend Shared ReadOnly Property _D126() As String
            Get
                Return ResourceManager.GetString("_D126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mode d&apos;affichage des éléments du groupe. .
        '''</summary>
        Friend Shared ReadOnly Property _D127() As String
            Get
                Return ResourceManager.GetString("_D127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Element image de la page sur lequel on affecte la zoom d&apos;image. Le zoom d&apos;image se déclenchera sur le clic de cette image..
        '''</summary>
        Friend Shared ReadOnly Property _D128() As String
            Get
                Return ResourceManager.GetString("_D128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Chemin de l&apos;image affiché en zoom..
        '''</summary>
        Friend Shared ReadOnly Property _D129() As String
            Get
                Return ResourceManager.GetString("_D129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre associé à votre image zoom. Ce titre apparaîtra en dessous de l&apos;image..
        '''</summary>
        Friend Shared ReadOnly Property _D130() As String
            Get
                Return ResourceManager.GetString("_D130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Description associée à votre image zoom. Cette description apparaîtra en dessous de l&apos;image..
        '''</summary>
        Friend Shared ReadOnly Property _D131() As String
            Get
                Return ResourceManager.GetString("_D131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien vers une page internet. Ce lien apparaîtra en dessous de l&apos;image..
        '''</summary>
        Friend Shared ReadOnly Property _D132() As String
            Get
                Return ResourceManager.GetString("_D132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Evénement déclencheur de l&apos;ouverture des sous menus..
        '''</summary>
        Friend Shared ReadOnly Property _D133() As String
            Get
                Return ResourceManager.GetString("_D133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lorsque l&apos;option est activée, la taille de tous les sous menu est  identique..
        '''</summary>
        Friend Shared ReadOnly Property _D134() As String
            Get
                Return ResourceManager.GetString("_D134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Durée d&apos;ouverture (en milliseconde).
        '''</summary>
        Friend Shared ReadOnly Property _D135() As String
            Get
                Return ResourceManager.GetString("_D135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur de fond des images JPG et GIF après redimensionnement.
        '''</summary>
        Friend Shared ReadOnly Property _D136() As String
            Get
                Return ResourceManager.GetString("_D136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration de la barre de partage sur les réseaux sociaux.
        '''</summary>
        Friend Shared ReadOnly Property _D137() As String
            Get
                Return ResourceManager.GetString("_D137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Type d&apos;effet appliqué lors de l&apos;animation..
        '''</summary>
        Friend Shared ReadOnly Property _D138() As String
            Get
                Return ResourceManager.GetString("_D138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration de l&apos;arborescence.
        '''</summary>
        Friend Shared ReadOnly Property _D139() As String
            Get
                Return ResourceManager.GetString("_D139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Indique si l&apos;arborescence doit être entièrement fermée ou ouverte à l&apos;ouverture de la page.
        '''</summary>
        Friend Shared ReadOnly Property _D140() As String
            Get
                Return ResourceManager.GetString("_D140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Indique si plusieurs lignes peuvent être ouvertes en même temps.
        '''</summary>
        Friend Shared ReadOnly Property _D141() As String
            Get
                Return ResourceManager.GetString("_D141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre de la ligne.
        '''</summary>
        Friend Shared ReadOnly Property _D142() As String
            Get
                Return ResourceManager.GetString("_D142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien de la ligne.
        '''</summary>
        Friend Shared ReadOnly Property _D143() As String
            Get
                Return ResourceManager.GetString("_D143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Icône de la ligne.
        '''</summary>
        Friend Shared ReadOnly Property _D144() As String
            Get
                Return ResourceManager.GetString("_D144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Permet au fond (background) de l&apos;élément d&apos;être transparent.
        '''</summary>
        Friend Shared ReadOnly Property _D145() As String
            Get
                Return ResourceManager.GetString("_D145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nœud ouvert au chargement de la page.
        '''</summary>
        Friend Shared ReadOnly Property _D146() As String
            Get
                Return ResourceManager.GetString("_D146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nœud fermé au chargement de la page.
        '''</summary>
        Friend Shared ReadOnly Property _D147() As String
            Get
                Return ResourceManager.GetString("_D147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration : choix du menu correspondant.
        '''</summary>
        Friend Shared ReadOnly Property _D148() As String
            Get
                Return ResourceManager.GetString("_D148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien sur la première image.
        '''</summary>
        Friend Shared ReadOnly Property _D149() As String
            Get
                Return ResourceManager.GetString("_D149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Première image.
        '''</summary>
        Friend Shared ReadOnly Property _D150() As String
            Get
                Return ResourceManager.GetString("_D150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image de séparation entre les liens.
        '''</summary>
        Friend Shared ReadOnly Property _D151() As String
            Get
                Return ResourceManager.GetString("_D151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration de l&apos;envoi d&apos;e-mails depuis le site (en PHP).
        '''</summary>
        Friend Shared ReadOnly Property _D152() As String
            Get
                Return ResourceManager.GetString("_D152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration du formulaire.
        '''</summary>
        Friend Shared ReadOnly Property _D153() As String
            Get
                Return ResourceManager.GetString("_D153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Les balises titres sont utilisées en référencement. Elles sont d&apos;ordre d&apos;importance décroissante (H1 vers H6) et contiennent un style graphique qui leur sont propres. (Attention ! certaines règles s&apos;appliquent à l&apos;utilisation de ces balises).
        '''</summary>
        Friend Shared ReadOnly Property _D154() As String
            Get
                Return ResourceManager.GetString("_D154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Largeur du cryptogramme (en pixels).
        '''</summary>
        Friend Shared ReadOnly Property _D155() As String
            Get
                Return ResourceManager.GetString("_D155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hauteur du cryptogramme (en pixels).
        '''</summary>
        Friend Shared ReadOnly Property _D156() As String
            Get
                Return ResourceManager.GetString("_D156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Temps (en seconde) avant d&apos;avoir le droit de regénérer un cryptogramme.
        '''</summary>
        Friend Shared ReadOnly Property _D157() As String
            Get
                Return ResourceManager.GetString("_D157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre maximum de fois que l&apos;utilisateur peut générer le cryptogramme.
        '''</summary>
        Friend Shared ReadOnly Property _D158() As String
            Get
                Return ResourceManager.GetString("_D158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur de base des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _D159() As String
            Get
                Return ResourceManager.GetString("_D159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choix aléatoire de la couleur..
        '''</summary>
        Friend Shared ReadOnly Property _D160() As String
            Get
                Return ResourceManager.GetString("_D160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Niveau de clarté des caractères si choix aléatoire (0-&gt;4).
        '''</summary>
        Friend Shared ReadOnly Property _D161() As String
            Get
                Return ResourceManager.GetString("_D161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Intensité de la transparence des caractères (0-&gt;127).
        '''</summary>
        Friend Shared ReadOnly Property _D162() As String
            Get
                Return ResourceManager.GetString("_D162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Police des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _D163() As String
            Get
                Return ResourceManager.GetString("_D163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Différencie les majuscules/minuscules lors de la saisie du code.
        '''</summary>
        Friend Shared ReadOnly Property _D164() As String
            Get
                Return ResourceManager.GetString("_D164", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre minimum de caractères dans le cryptogramme.
        '''</summary>
        Friend Shared ReadOnly Property _D165() As String
            Get
                Return ResourceManager.GetString("_D165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre maximum de caractères dans le cryptogramme.
        '''</summary>
        Friend Shared ReadOnly Property _D166() As String
            Get
                Return ResourceManager.GetString("_D166", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Espace entre les caractères (en pixels).
        '''</summary>
        Friend Shared ReadOnly Property _D167() As String
            Get
                Return ResourceManager.GetString("_D167", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille minimum des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _D168() As String
            Get
                Return ResourceManager.GetString("_D168", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille maximum des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _D169() As String
            Get
                Return ResourceManager.GetString("_D169", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Angle maximum de rotation des caractères (0-360).
        '''</summary>
        Friend Shared ReadOnly Property _D170() As String
            Get
                Return ResourceManager.GetString("_D170", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Déplacement vertical aléatoire des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _D171() As String
            Get
                Return ResourceManager.GetString("_D171", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre minimum de pixels aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _D172() As String
            Get
                Return ResourceManager.GetString("_D172", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre maximum de pixels aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _D173() As String
            Get
                Return ResourceManager.GetString("_D173", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre minimum de lignes aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _D174() As String
            Get
                Return ResourceManager.GetString("_D174", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre maximum de lignes aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _D175() As String
            Get
                Return ResourceManager.GetString("_D175", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre minimum de cercles aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _D176() As String
            Get
                Return ResourceManager.GetString("_D176", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre maximum de cercles aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _D177() As String
            Get
                Return ResourceManager.GetString("_D177", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur d&apos;écriture des pixels, lignes, cercles.
        '''</summary>
        Friend Shared ReadOnly Property _D178() As String
            Get
                Return ResourceManager.GetString("_D178", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille d&apos;écriture du pinceau (en pixels).
        '''</summary>
        Friend Shared ReadOnly Property _D179() As String
            Get
                Return ResourceManager.GetString("_D179", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le bruit est-il par dessus l&apos;ecriture (coché) ou en dessous.
        '''</summary>
        Friend Shared ReadOnly Property _D180() As String
            Get
                Return ResourceManager.GetString("_D180", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Caractères qui seront affichés dans le cryptogramme.
        '''</summary>
        Friend Shared ReadOnly Property _D181() As String
            Get
                Return ResourceManager.GetString("_D181", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Message affiché en cas d&apos;erreur dans l&apos;exécution du captcha.
        '''</summary>
        Friend Shared ReadOnly Property _D182() As String
            Get
                Return ResourceManager.GetString("_D182", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liens vers les sources vidéos: - MP4 est exigé; - la source &quot;alternative&quot; en format OGG ou WebM permets le mode HTML5 (au lieu de Flash ou QuickTime) avec Firefox, Opera etc..
        '''</summary>
        Friend Shared ReadOnly Property _D183() As String
            Get
                Return ResourceManager.GetString("_D183", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image à afficher au début de la vidéo (Il est conseillé de garder la proportion &quot;largeur/hauteur&quot; de la vidéo pour l&apos;image) avant lancement de lecture de celle-ci..
        '''</summary>
        Friend Shared ReadOnly Property _D184() As String
            Get
                Return ResourceManager.GetString("_D184", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisation de la configuration &quot;par défaut&quot; (le design etc. dépend d&apos;un navigateur) des contrôles de lecture.
        '''</summary>
        Friend Shared ReadOnly Property _D185() As String
            Get
                Return ResourceManager.GetString("_D185", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisation d&apos;une configuration  personnalisée (design ajustable) des contrôles de lecture.
        '''</summary>
        Friend Shared ReadOnly Property _D186() As String
            Get
                Return ResourceManager.GetString("_D186", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La Lecture  démarre automatiquement après le chargement de la page..
        '''</summary>
        Friend Shared ReadOnly Property _D187() As String
            Get
                Return ResourceManager.GetString("_D187", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La lecture s&apos;effectue en boucle  (pas soutenue par le navigateur Opera).
        '''</summary>
        Friend Shared ReadOnly Property _D188() As String
            Get
                Return ResourceManager.GetString("_D188", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Désactivation du son.
        '''</summary>
        Friend Shared ReadOnly Property _D189() As String
            Get
                Return ResourceManager.GetString("_D189", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Message affiché si Flash et QuickTime (ou uniquement Flash en cas d&apos;Internet Explorer) ne sont pas disponibles.
        '''</summary>
        Friend Shared ReadOnly Property _D190() As String
            Get
                Return ResourceManager.GetString("_D190", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage des barres de défilement.
        '''</summary>
        Friend Shared ReadOnly Property _D191() As String
            Get
                Return ResourceManager.GetString("_D191", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage des bordures.
        '''</summary>
        Friend Shared ReadOnly Property _D192() As String
            Get
                Return ResourceManager.GetString("_D192", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Script du bouton PayPal.
        '''</summary>
        Friend Shared ReadOnly Property _D193() As String
            Get
                Return ResourceManager.GetString("_D193", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Paramètres à envoyer au flash.
        '''</summary>
        Friend Shared ReadOnly Property _D194() As String
            Get
                Return ResourceManager.GetString("_D194", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du paramètre.
        '''</summary>
        Friend Shared ReadOnly Property _D195() As String
            Get
                Return ResourceManager.GetString("_D195", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur du paramètre.
        '''</summary>
        Friend Shared ReadOnly Property _D196() As String
            Get
                Return ResourceManager.GetString("_D196", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de colonne du tableau.
        '''</summary>
        Friend Shared ReadOnly Property _D197() As String
            Get
                Return ResourceManager.GetString("_D197", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de ligne du tableau.
        '''</summary>
        Friend Shared ReadOnly Property _D198() As String
            Get
                Return ResourceManager.GetString("_D198", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Afficher les indicateurs de lignes et de colonnes.
        '''</summary>
        Friend Shared ReadOnly Property _D199() As String
            Get
                Return ResourceManager.GetString("_D199", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à URL du flux RSS.
        '''</summary>
        Friend Shared ReadOnly Property _D200() As String
            Get
                Return ResourceManager.GetString("_D200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tant que le tableau est verrouillé, il est impossible de modifier son contenu.
        '''</summary>
        Friend Shared ReadOnly Property _D201() As String
            Get
                Return ResourceManager.GetString("_D201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre de l&apos;article.
        '''</summary>
        Friend Shared ReadOnly Property _D202() As String
            Get
                Return ResourceManager.GetString("_D202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Date de création de l&apos;article.
        '''</summary>
        Friend Shared ReadOnly Property _D203() As String
            Get
                Return ResourceManager.GetString("_D203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Contenu de l&apos;article.
        '''</summary>
        Friend Shared ReadOnly Property _D204() As String
            Get
                Return ResourceManager.GetString("_D204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien vers la page contenant l&apos;article.
        '''</summary>
        Friend Shared ReadOnly Property _D205() As String
            Get
                Return ResourceManager.GetString("_D205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Indication provenance de l&apos;article.
        '''</summary>
        Friend Shared ReadOnly Property _D206() As String
            Get
                Return ResourceManager.GetString("_D206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à [name] Nom du champ dans le HTML.
        '''</summary>
        Friend Shared ReadOnly Property _D207() As String
            Get
                Return ResourceManager.GetString("_D207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ligne sélectionnée.
        '''</summary>
        Friend Shared ReadOnly Property _D209() As String
            Get
                Return ResourceManager.GetString("_D209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Type du champ.
        '''</summary>
        Friend Shared ReadOnly Property _D210() As String
            Get
                Return ResourceManager.GetString("_D210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à HTML5 - [autocomplete] Activation ou désactivation  du remplissage automatique du champ par le navigateur. 
        '''Le navigateur propose les valeurs déjà saisie dans d&apos;autres champs ayant eu le même attribut [name]..
        '''</summary>
        Friend Shared ReadOnly Property _D211() As String
            Get
                Return ResourceManager.GetString("_D211", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à HTML5 - [multiple] Permet à l&apos;utilisateur à choisir plusieurs fichiers. .
        '''</summary>
        Friend Shared ReadOnly Property _D212() As String
            Get
                Return ResourceManager.GetString("_D212", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annulation de la possibilité de redimensionnement par les visiteurs sous Chrome et Firefox..
        '''</summary>
        Friend Shared ReadOnly Property _D213() As String
            Get
                Return ResourceManager.GetString("_D213", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position de départ de l&apos;onglet.
        '''</summary>
        Friend Shared ReadOnly Property _D214() As String
            Get
                Return ResourceManager.GetString("_D214", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ouverture de l&apos;onglet au chargement de la page.
        '''</summary>
        Friend Shared ReadOnly Property _D215() As String
            Get
                Return ResourceManager.GetString("_D215", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Entête du flux Rss.
        '''</summary>
        Friend Shared ReadOnly Property _D216() As String
            Get
                Return ResourceManager.GetString("_D216", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste des articles.
        '''</summary>
        Friend Shared ReadOnly Property _D217() As String
            Get
                Return ResourceManager.GetString("_D217", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste des pages.
        '''</summary>
        Friend Shared ReadOnly Property _D218() As String
            Get
                Return ResourceManager.GetString("_D218", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Element précèdent.
        '''</summary>
        Friend Shared ReadOnly Property _D219() As String
            Get
                Return ResourceManager.GetString("_D219", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Element suivant.
        '''</summary>
        Friend Shared ReadOnly Property _D220() As String
            Get
                Return ResourceManager.GetString("_D220", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Direction du défilement.
        '''</summary>
        Friend Shared ReadOnly Property _D221() As String
            Get
                Return ResourceManager.GetString("_D221", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Temps de défilement.
        '''</summary>
        Friend Shared ReadOnly Property _D222() As String
            Get
                Return ResourceManager.GetString("_D222", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Elément d&apos;accès direct à cette page.
        '''</summary>
        Friend Shared ReadOnly Property _D223() As String
            Get
                Return ResourceManager.GetString("_D223", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Elément permettant d&apos;aller à la page précédente.
        '''</summary>
        Friend Shared ReadOnly Property _D224() As String
            Get
                Return ResourceManager.GetString("_D224", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Elément permettant d&apos;aller à la page suivante.
        '''</summary>
        Friend Shared ReadOnly Property _D225() As String
            Get
                Return ResourceManager.GetString("_D225", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage automatique du défilement.
        '''</summary>
        Friend Shared ReadOnly Property _D226() As String
            Get
                Return ResourceManager.GetString("_D226", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Arrêt du défilement au passage de la souris au-dessus du diaporama.
        '''</summary>
        Friend Shared ReadOnly Property _D227() As String
            Get
                Return ResourceManager.GetString("_D227", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai de démarrage du défilement.
        '''</summary>
        Friend Shared ReadOnly Property _D228() As String
            Get
                Return ResourceManager.GetString("_D228", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Elément permettant de lancer le défilement du diaporama.
        '''</summary>
        Friend Shared ReadOnly Property _D229() As String
            Get
                Return ResourceManager.GetString("_D229", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Elément permettant d&apos;arreter le défilement du diaporama.
        '''</summary>
        Friend Shared ReadOnly Property _D230() As String
            Get
                Return ResourceManager.GetString("_D230", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le diaporama defile de façon continu.
        '''</summary>
        Friend Shared ReadOnly Property _D231() As String
            Get
                Return ResourceManager.GetString("_D231", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effet de ralenti.
        '''</summary>
        Friend Shared ReadOnly Property _D232() As String
            Get
                Return ResourceManager.GetString("_D232", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Espace entre les pages du diaporama.
        '''</summary>
        Friend Shared ReadOnly Property _D233() As String
            Get
                Return ResourceManager.GetString("_D233", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mode d&apos;affichage des pages.
        '''</summary>
        Friend Shared ReadOnly Property _D234() As String
            Get
                Return ResourceManager.GetString("_D234", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effet de ralenti à l&apos;ouverture de l&apos;onglet.
        '''</summary>
        Friend Shared ReadOnly Property _D235() As String
            Get
                Return ResourceManager.GetString("_D235", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effet de ralenti à la fermeture de l&apos;onglet.
        '''</summary>
        Friend Shared ReadOnly Property _D236() As String
            Get
                Return ResourceManager.GetString("_D236", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration de la liste des drapeaux affichés.
        '''</summary>
        Friend Shared ReadOnly Property _D237() As String
            Get
                Return ResourceManager.GetString("_D237", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Source du paquet.
        '''</summary>
        Friend Shared ReadOnly Property _D238() As String
            Get
                Return ResourceManager.GetString("_D238", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélectionner les éléments.
        '''</summary>
        Friend Shared ReadOnly Property _D239() As String
            Get
                Return ResourceManager.GetString("_D239", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attribuer les sources (valeurs).
        '''</summary>
        Friend Shared ReadOnly Property _D240() As String
            Get
                Return ResourceManager.GetString("_D240", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Transferer les paramètres URL actuels à la page-cible.
        '''</summary>
        Friend Shared ReadOnly Property _D241() As String
            Get
                Return ResourceManager.GetString("_D241", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai avant démarrage de l&apos;ouverture du sous menu.
        '''</summary>
        Friend Shared ReadOnly Property _D242() As String
            Get
                Return ResourceManager.GetString("_D242", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai avant démarrage de la fermeture du sous menu.
        '''</summary>
        Friend Shared ReadOnly Property _D243() As String
            Get
                Return ResourceManager.GetString("_D243", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Permettre d&apos;utiliser la liste dynamique, par exemple venant d&apos;une base de données.
        '''</summary>
        Friend Shared ReadOnly Property _D244() As String
            Get
                Return ResourceManager.GetString("_D244", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
