'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4984
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources.text
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizableFormAndConverter
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebElement.LocalizableFormAndConverter", GetType(LocalizableFormAndConverter).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tableau de données.
        '''</summary>
        Friend Shared ReadOnly Property _0001() As String
            Get
                Return ResourceManager.GetString("_0001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Automatique.
        '''</summary>
        Friend Shared ReadOnly Property _0002() As String
            Get
                Return ResourceManager.GetString("_0002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Toujours visible.
        '''</summary>
        Friend Shared ReadOnly Property _0003() As String
            Get
                Return ResourceManager.GetString("_0003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Jamais visible.
        '''</summary>
        Friend Shared ReadOnly Property _0004() As String
            Get
                Return ResourceManager.GetString("_0004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A gauche-haut.
        '''</summary>
        Friend Shared ReadOnly Property _0005() As String
            Get
                Return ResourceManager.GetString("_0005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A gauche-milieu.
        '''</summary>
        Friend Shared ReadOnly Property _0006() As String
            Get
                Return ResourceManager.GetString("_0006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A gauche-bas.
        '''</summary>
        Friend Shared ReadOnly Property _0007() As String
            Get
                Return ResourceManager.GetString("_0007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Au-dessus.
        '''</summary>
        Friend Shared ReadOnly Property _0008() As String
            Get
                Return ResourceManager.GetString("_0008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A droite-haut.
        '''</summary>
        Friend Shared ReadOnly Property _0009() As String
            Get
                Return ResourceManager.GetString("_0009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A droite-milieu.
        '''</summary>
        Friend Shared ReadOnly Property _0010() As String
            Get
                Return ResourceManager.GetString("_0010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A droite-bas.
        '''</summary>
        Friend Shared ReadOnly Property _0011() As String
            Get
                Return ResourceManager.GetString("_0011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En-dessous.
        '''</summary>
        Friend Shared ReadOnly Property _0012() As String
            Get
                Return ResourceManager.GetString("_0012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0013() As String
            Get
                Return ResourceManager.GetString("_0013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A droite.
        '''</summary>
        Friend Shared ReadOnly Property _0014() As String
            Get
                Return ResourceManager.GetString("_0014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun.
        '''</summary>
        Friend Shared ReadOnly Property _0015() As String
            Get
                Return ResourceManager.GetString("_0015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Horizontal-bas.
        '''</summary>
        Friend Shared ReadOnly Property _0016() As String
            Get
                Return ResourceManager.GetString("_0016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Horizontal-gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0017() As String
            Get
                Return ResourceManager.GetString("_0017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Horizontal-droite.
        '''</summary>
        Friend Shared ReadOnly Property _0018() As String
            Get
                Return ResourceManager.GetString("_0018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Horizontal-haut.
        '''</summary>
        Friend Shared ReadOnly Property _0019() As String
            Get
                Return ResourceManager.GetString("_0019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical-bas.
        '''</summary>
        Friend Shared ReadOnly Property _0020() As String
            Get
                Return ResourceManager.GetString("_0020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical-gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0021() As String
            Get
                Return ResourceManager.GetString("_0021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical-droite.
        '''</summary>
        Friend Shared ReadOnly Property _0022() As String
            Get
                Return ResourceManager.GetString("_0022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical-haut.
        '''</summary>
        Friend Shared ReadOnly Property _0023() As String
            Get
                Return ResourceManager.GetString("_0023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical aligné-bas.
        '''</summary>
        Friend Shared ReadOnly Property _0024() As String
            Get
                Return ResourceManager.GetString("_0024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical aligné-gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0025() As String
            Get
                Return ResourceManager.GetString("_0025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical aligné-droite.
        '''</summary>
        Friend Shared ReadOnly Property _0026() As String
            Get
                Return ResourceManager.GetString("_0026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vertical aligné-haut.
        '''</summary>
        Friend Shared ReadOnly Property _0027() As String
            Get
                Return ResourceManager.GetString("_0027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Horizontale.
        '''</summary>
        Friend Shared ReadOnly Property _0028() As String
            Get
                Return ResourceManager.GetString("_0028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Verticale.
        '''</summary>
        Friend Shared ReadOnly Property _0029() As String
            Get
                Return ResourceManager.GetString("_0029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Verticale alignée.
        '''</summary>
        Friend Shared ReadOnly Property _0030() As String
            Get
                Return ResourceManager.GetString("_0030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Au milieu.
        '''</summary>
        Friend Shared ReadOnly Property _0031() As String
            Get
                Return ResourceManager.GetString("_0031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du champ 1.
        '''</summary>
        Friend Shared ReadOnly Property _0032() As String
            Get
                Return ResourceManager.GetString("_0032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du champ 2.
        '''</summary>
        Friend Shared ReadOnly Property _0033() As String
            Get
                Return ResourceManager.GetString("_0033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur 1.
        '''</summary>
        Friend Shared ReadOnly Property _0034() As String
            Get
                Return ResourceManager.GetString("_0034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur 2.
        '''</summary>
        Friend Shared ReadOnly Property _0035() As String
            Get
                Return ResourceManager.GetString("_0035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Les informations suivantes sont obligatoires : .
        '''</summary>
        Friend Shared ReadOnly Property _0036() As String
            Get
                Return ResourceManager.GetString("_0036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - l&apos;adresse de réception de l&apos;e-mail..
        '''</summary>
        Friend Shared ReadOnly Property _0037() As String
            Get
                Return ResourceManager.GetString("_0037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le sujet de l&apos;e-mail..
        '''</summary>
        Friend Shared ReadOnly Property _0038() As String
            Get
                Return ResourceManager.GetString("_0038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le sujet de l&apos;accusé de réception (car vous avez coché la case)..
        '''</summary>
        Friend Shared ReadOnly Property _0039() As String
            Get
                Return ResourceManager.GetString("_0039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le message de l&apos;accusé de réception(car vous avez coché la case)..
        '''</summary>
        Friend Shared ReadOnly Property _0040() As String
            Get
                Return ResourceManager.GetString("_0040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0041() As String
            Get
                Return ResourceManager.GetString("_0041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Droite.
        '''</summary>
        Friend Shared ReadOnly Property _0042() As String
            Get
                Return ResourceManager.GetString("_0042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Haut.
        '''</summary>
        Friend Shared ReadOnly Property _0043() As String
            Get
                Return ResourceManager.GetString("_0043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moyenne haute.
        '''</summary>
        Friend Shared ReadOnly Property _0044() As String
            Get
                Return ResourceManager.GetString("_0044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moyenne basse.
        '''</summary>
        Friend Shared ReadOnly Property _0045() As String
            Get
                Return ResourceManager.GetString("_0045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parfaite.
        '''</summary>
        Friend Shared ReadOnly Property _0046() As String
            Get
                Return ResourceManager.GetString("_0046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supérieure.
        '''</summary>
        Friend Shared ReadOnly Property _0047() As String
            Get
                Return ResourceManager.GetString("_0047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Inférieure.
        '''</summary>
        Friend Shared ReadOnly Property _0048() As String
            Get
                Return ResourceManager.GetString("_0048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moyenne.
        '''</summary>
        Friend Shared ReadOnly Property _0049() As String
            Get
                Return ResourceManager.GetString("_0049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Haut gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0050() As String
            Get
                Return ResourceManager.GetString("_0050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Haut droit.
        '''</summary>
        Friend Shared ReadOnly Property _0051() As String
            Get
                Return ResourceManager.GetString("_0051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Proportionnelle.
        '''</summary>
        Friend Shared ReadOnly Property _0053() As String
            Get
                Return ResourceManager.GetString("_0053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Non-proportionnelle.
        '''</summary>
        Friend Shared ReadOnly Property _0054() As String
            Get
                Return ResourceManager.GetString("_0054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fenêtre.
        '''</summary>
        Friend Shared ReadOnly Property _0055() As String
            Get
                Return ResourceManager.GetString("_0055", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Opaque.
        '''</summary>
        Friend Shared ReadOnly Property _0056() As String
            Get
                Return ResourceManager.GetString("_0056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Transparent.
        '''</summary>
        Friend Shared ReadOnly Property _0057() As String
            Get
                Return ResourceManager.GetString("_0057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tous.
        '''</summary>
        Friend Shared ReadOnly Property _0058() As String
            Get
                Return ResourceManager.GetString("_0058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pas de contrôle.
        '''</summary>
        Friend Shared ReadOnly Property _0059() As String
            Get
                Return ResourceManager.GetString("_0059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pas d&apos;affichage.
        '''</summary>
        Friend Shared ReadOnly Property _0060() As String
            Get
                Return ResourceManager.GetString("_0060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir le permalink de votre vidéo.
        '''</summary>
        Friend Shared ReadOnly Property _0061() As String
            Get
                Return ResourceManager.GetString("_0061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir l&apos;URL&apos; de votre vidéo.
        '''</summary>
        Friend Shared ReadOnly Property _0062() As String
            Get
                Return ResourceManager.GetString("_0062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Clic.
        '''</summary>
        Friend Shared ReadOnly Property _0063() As String
            Get
                Return ResourceManager.GetString("_0063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Double clic.
        '''</summary>
        Friend Shared ReadOnly Property _0064() As String
            Get
                Return ResourceManager.GetString("_0064", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Au dessus ou clic (Recommandé).
        '''</summary>
        Friend Shared ReadOnly Property _0065() As String
            Get
                Return ResourceManager.GetString("_0065", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En bas à gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0066() As String
            Get
                Return ResourceManager.GetString("_0066", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En haut à gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0067() As String
            Get
                Return ResourceManager.GetString("_0067", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En bas à droite.
        '''</summary>
        Friend Shared ReadOnly Property _0069() As String
            Get
                Return ResourceManager.GetString("_0069", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En haut à droite.
        '''</summary>
        Friend Shared ReadOnly Property _0070() As String
            Get
                Return ResourceManager.GetString("_0070", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible de trouver ce menu.
        '''</summary>
        Friend Shared ReadOnly Property _0071() As String
            Get
                Return ResourceManager.GetString("_0071", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Souhaitez vous supprimer ce séparateur ?.
        '''</summary>
        Friend Shared ReadOnly Property _0072() As String
            Get
                Return ResourceManager.GetString("_0072", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Souhaitez vous supprimer le menu : {0} ?.
        '''</summary>
        Friend Shared ReadOnly Property _0073() As String
            Get
                Return ResourceManager.GetString("_0073", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible de modifier un séparateur..
        '''</summary>
        Friend Shared ReadOnly Property _0074() As String
            Get
                Return ResourceManager.GetString("_0074", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir :.
        '''</summary>
        Friend Shared ReadOnly Property _0075() As String
            Get
                Return ResourceManager.GetString("_0075", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - un élément déclencheur.
        '''</summary>
        Friend Shared ReadOnly Property _0076() As String
            Get
                Return ResourceManager.GetString("_0076", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - un élément accrocheur.
        '''</summary>
        Friend Shared ReadOnly Property _0077() As String
            Get
                Return ResourceManager.GetString("_0077", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - un événement.
        '''</summary>
        Friend Shared ReadOnly Property _0078() As String
            Get
                Return ResourceManager.GetString("_0078", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Depuis le début.
        '''</summary>
        Friend Shared ReadOnly Property _0079() As String
            Get
                Return ResourceManager.GetString("_0079", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Journalier.
        '''</summary>
        Friend Shared ReadOnly Property _0080() As String
            Get
                Return ResourceManager.GetString("_0080", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hebdomadaire.
        '''</summary>
        Friend Shared ReadOnly Property _0081() As String
            Get
                Return ResourceManager.GetString("_0081", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mensuel.
        '''</summary>
        Friend Shared ReadOnly Property _0082() As String
            Get
                Return ResourceManager.GetString("_0082", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuel.
        '''</summary>
        Friend Shared ReadOnly Property _0083() As String
            Get
                Return ResourceManager.GetString("_0083", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez sélectionner un menu..
        '''</summary>
        Friend Shared ReadOnly Property _0085() As String
            Get
                Return ResourceManager.GetString("_0085", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez sélectionner un élément accrocheur..
        '''</summary>
        Friend Shared ReadOnly Property _0086() As String
            Get
                Return ResourceManager.GetString("_0086", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez sélectionner : 
        '''   - l&apos;élément accrocheur
        '''   - l&apos;événement déclencheur.
        '''</summary>
        Friend Shared ReadOnly Property _0087() As String
            Get
                Return ResourceManager.GetString("_0087", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez sélectionner un ou plusieurs éléments déclencheurs..
        '''</summary>
        Friend Shared ReadOnly Property _0088() As String
            Get
                Return ResourceManager.GetString("_0088", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En haut.
        '''</summary>
        Friend Shared ReadOnly Property _0089() As String
            Get
                Return ResourceManager.GetString("_0089", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En bas.
        '''</summary>
        Friend Shared ReadOnly Property _0090() As String
            Get
                Return ResourceManager.GetString("_0090", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à De droite à gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0091() As String
            Get
                Return ResourceManager.GetString("_0091", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à De gauche à droite.
        '''</summary>
        Friend Shared ReadOnly Property _0092() As String
            Get
                Return ResourceManager.GetString("_0092", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Par défaut.
        '''</summary>
        Friend Shared ReadOnly Property _0093() As String
            Get
                Return ResourceManager.GetString("_0093", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention, les données suivantes sont indispensables pour l&apos;envoi du formulaire.
        '''{0}
        '''Souhaitez-vous les saisir ?.
        '''</summary>
        Friend Shared ReadOnly Property _0094() As String
            Get
                Return ResourceManager.GetString("_0094", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - l&apos;adresse de réception de l&apos;e-mail.
        '''</summary>
        Friend Shared ReadOnly Property _0095() As String
            Get
                Return ResourceManager.GetString("_0095", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le sujet l&apos;e-mail.
        '''</summary>
        Friend Shared ReadOnly Property _0096() As String
            Get
                Return ResourceManager.GetString("_0096", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - l&apos;adresse de l&apos;expéditeur de l&apos;e-mail.
        '''</summary>
        Friend Shared ReadOnly Property _0097() As String
            Get
                Return ResourceManager.GetString("_0097", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le sujet de l&apos;accusé de réception.
        '''</summary>
        Friend Shared ReadOnly Property _0098() As String
            Get
                Return ResourceManager.GetString("_0098", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le message de l&apos;accusé de réception.
        '''</summary>
        Friend Shared ReadOnly Property _0099() As String
            Get
                Return ResourceManager.GetString("_0099", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - l&apos;élément contenant l&apos;adresse e-mail du visiteur.
        '''</summary>
        Friend Shared ReadOnly Property _0100() As String
            Get
                Return ResourceManager.GetString("_0100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le message de réussite de l&apos;envoi.
        '''</summary>
        Friend Shared ReadOnly Property _0101() As String
            Get
                Return ResourceManager.GetString("_0101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le message d&apos;échec de l&apos;envoi.
        '''</summary>
        Friend Shared ReadOnly Property _0102() As String
            Get
                Return ResourceManager.GetString("_0102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - les éléments du formulaire à prendre en compte pour l&apos;envoi.
        '''</summary>
        Friend Shared ReadOnly Property _0103() As String
            Get
                Return ResourceManager.GetString("_0103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à - le bouton d&apos;envoi du formulaire.
        '''</summary>
        Friend Shared ReadOnly Property _0104() As String
            Get
                Return ResourceManager.GetString("_0104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre.
        '''</summary>
        Friend Shared ReadOnly Property _0109() As String
            Get
                Return ResourceManager.GetString("_0109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Description.
        '''</summary>
        Friend Shared ReadOnly Property _0110() As String
            Get
                Return ResourceManager.GetString("_0110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter une image.
        '''</summary>
        Friend Shared ReadOnly Property _0111() As String
            Get
                Return ResourceManager.GetString("_0111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition de l&apos;image.
        '''</summary>
        Friend Shared ReadOnly Property _0112() As String
            Get
                Return ResourceManager.GetString("_0112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Gestion des listes.
        '''</summary>
        Friend Shared ReadOnly Property _0113() As String
            Get
                Return ResourceManager.GetString("_0113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Au-dessus.
        '''</summary>
        Friend Shared ReadOnly Property _0114() As String
            Get
                Return ResourceManager.GetString("_0114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Quitter sans sauvegarder ?.
        '''</summary>
        Friend Shared ReadOnly Property _0115() As String
            Get
                Return ResourceManager.GetString("_0115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez sélectionner l&apos;élément image que vous souhaitez zoomer..
        '''</summary>
        Friend Shared ReadOnly Property _0116() As String
            Get
                Return ResourceManager.GetString("_0116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez sélectionner une image.
        '''</summary>
        Friend Shared ReadOnly Property _0117() As String
            Get
                Return ResourceManager.GetString("_0117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à En début de document.
        '''</summary>
        Friend Shared ReadOnly Property _0118() As String
            Get
                Return ResourceManager.GetString("_0118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sauvegarder la configuration ?.
        '''</summary>
        Friend Shared ReadOnly Property _0119() As String
            Get
                Return ResourceManager.GetString("_0119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez renseigner le nom du compte  twitter à suivre..
        '''</summary>
        Friend Shared ReadOnly Property _0120() As String
            Get
                Return ResourceManager.GetString("_0120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez renseigner l&apos;adresse de la page facebook..
        '''</summary>
        Friend Shared ReadOnly Property _0121() As String
            Get
                Return ResourceManager.GetString("_0121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;adresse est erronée, elle doit avoir la forme suivante : &quot;https://www.facebook.com/...&quot;..
        '''</summary>
        Friend Shared ReadOnly Property _0122() As String
            Get
                Return ResourceManager.GetString("_0122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Linéaire.
        '''</summary>
        Friend Shared ReadOnly Property _0123() As String
            Get
                Return ResourceManager.GetString("_0123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Oscillement.
        '''</summary>
        Friend Shared ReadOnly Property _0124() As String
            Get
                Return ResourceManager.GetString("_0124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Séquentiel.
        '''</summary>
        Friend Shared ReadOnly Property _0125() As String
            Get
                Return ResourceManager.GetString("_0125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Du bas vers le haut.
        '''</summary>
        Friend Shared ReadOnly Property _0126() As String
            Get
                Return ResourceManager.GetString("_0126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Du haut vers le bas.
        '''</summary>
        Friend Shared ReadOnly Property _0127() As String
            Get
                Return ResourceManager.GetString("_0127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Chargement des images.
        '''</summary>
        Friend Shared ReadOnly Property _0128() As String
            Get
                Return ResourceManager.GetString("_0128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;H1&gt;.
        '''</summary>
        Friend Shared ReadOnly Property _0129() As String
            Get
                Return ResourceManager.GetString("_0129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;H2&gt;.
        '''</summary>
        Friend Shared ReadOnly Property _0130() As String
            Get
                Return ResourceManager.GetString("_0130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;H3&gt;.
        '''</summary>
        Friend Shared ReadOnly Property _0131() As String
            Get
                Return ResourceManager.GetString("_0131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;H4&gt;.
        '''</summary>
        Friend Shared ReadOnly Property _0132() As String
            Get
                Return ResourceManager.GetString("_0132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;H5&gt;.
        '''</summary>
        Friend Shared ReadOnly Property _0133() As String
            Get
                Return ResourceManager.GetString("_0133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;H6&gt;.
        '''</summary>
        Friend Shared ReadOnly Property _0134() As String
            Get
                Return ResourceManager.GetString("_0134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleurs foncées.
        '''</summary>
        Friend Shared ReadOnly Property _0135() As String
            Get
                Return ResourceManager.GetString("_0135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleurs claires.
        '''</summary>
        Friend Shared ReadOnly Property _0136() As String
            Get
                Return ResourceManager.GetString("_0136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleurs neutres.
        '''</summary>
        Friend Shared ReadOnly Property _0137() As String
            Get
                Return ResourceManager.GetString("_0137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleurs très foncées.
        '''</summary>
        Friend Shared ReadOnly Property _0138() As String
            Get
                Return ResourceManager.GetString("_0138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleurs très claires.
        '''</summary>
        Friend Shared ReadOnly Property _0139() As String
            Get
                Return ResourceManager.GetString("_0139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Prédéfinies.
        '''</summary>
        Friend Shared ReadOnly Property _0140() As String
            Get
                Return ResourceManager.GetString("_0140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _0141() As String
            Get
                Return ResourceManager.GetString("_0141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pour regarder cette vidéo, il faut télécharger ou activer:.
        '''</summary>
        Friend Shared ReadOnly Property _0142() As String
            Get
                Return ResourceManager.GetString("_0142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à télécharger.
        '''</summary>
        Friend Shared ReadOnly Property _0143() As String
            Get
                Return ResourceManager.GetString("_0143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ou.
        '''</summary>
        Friend Shared ReadOnly Property _0144() As String
            Get
                Return ResourceManager.GetString("_0144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pas de source vidéo compatible.
        '''</summary>
        Friend Shared ReadOnly Property _0145() As String
            Get
                Return ResourceManager.GetString("_0145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention, suite au changement de script de Dailymotion, il faut remplacer votre lien par le nouveau code d&apos;intégration fourni par le site..
        '''</summary>
        Friend Shared ReadOnly Property _0146() As String
            Get
                Return ResourceManager.GetString("_0146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Remarque : Au moment de l&apos;installation du logiciel gratuit Freemake Vidéo Converter, par défaut le logiciel vous proposera d&apos;installer un plug-in à votre navigateur web et de modifier votre page d&apos;accueil par défaut. Décochez la case &quot;Defaut Installation&quot; ainsi que les autres cases si vous ne souhaitez pas que cela soit mise en place..
        '''</summary>
        Friend Shared ReadOnly Property _0147() As String
            Get
                Return ResourceManager.GetString("_0147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Auto.
        '''</summary>
        Friend Shared ReadOnly Property _0148() As String
            Get
                Return ResourceManager.GetString("_0148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Non.
        '''</summary>
        Friend Shared ReadOnly Property _0149() As String
            Get
                Return ResourceManager.GetString("_0149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Oui.
        '''</summary>
        Friend Shared ReadOnly Property _0150() As String
            Get
                Return ResourceManager.GetString("_0150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un paramètre.
        '''</summary>
        Friend Shared ReadOnly Property _0151() As String
            Get
                Return ResourceManager.GetString("_0151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Gestion des paramètres.
        '''</summary>
        Friend Shared ReadOnly Property _0152() As String
            Get
                Return ResourceManager.GetString("_0152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property _0153() As String
            Get
                Return ResourceManager.GetString("_0153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;image au chemin d&apos;accès suivant est corrompu et ne pourra donc être affichée..
        '''</summary>
        Friend Shared ReadOnly Property _0154() As String
            Get
                Return ResourceManager.GetString("_0154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image incorrect.
        '''</summary>
        Friend Shared ReadOnly Property _0155() As String
            Get
                Return ResourceManager.GetString("_0155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre du groupe 1.
        '''</summary>
        Friend Shared ReadOnly Property _0156() As String
            Get
                Return ResourceManager.GetString("_0156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nouveau champs.
        '''</summary>
        Friend Shared ReadOnly Property _0157() As String
            Get
                Return ResourceManager.GetString("_0157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur.
        '''</summary>
        Friend Shared ReadOnly Property _0158() As String
            Get
                Return ResourceManager.GetString("_0158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirmation.
        '''</summary>
        Friend Shared ReadOnly Property _0159() As String
            Get
                Return ResourceManager.GetString("_0159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La même fenêtre.
        '''</summary>
        Friend Shared ReadOnly Property _0160() As String
            Get
                Return ResourceManager.GetString("_0160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une nouvelle fenêtre.
        '''</summary>
        Friend Shared ReadOnly Property _0161() As String
            Get
                Return ResourceManager.GetString("_0161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La fenêtre &apos;parent&apos;.
        '''</summary>
        Friend Shared ReadOnly Property _0162() As String
            Get
                Return ResourceManager.GetString("_0162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à La fenêtre &apos;Top&apos;.
        '''</summary>
        Friend Shared ReadOnly Property _0163() As String
            Get
                Return ResourceManager.GetString("_0163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention un formulaire contenant un champ de téléchargement doit être configuré avec :
        '''Méthode = &apos;Post&apos;
        '''Enctype = &apos;multipart/form-data&apos;.
        '''</summary>
        Friend Shared ReadOnly Property _0164() As String
            Get
                Return ResourceManager.GetString("_0164", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir une adresse de destination pour le formulaire !.
        '''</summary>
        Friend Shared ReadOnly Property _0165() As String
            Get
                Return ResourceManager.GetString("_0165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez choisir un bouton annuler différent du bouton d&apos;envoi !.
        '''</summary>
        Friend Shared ReadOnly Property _0166() As String
            Get
                Return ResourceManager.GetString("_0166", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez séléctionner les éléments du formulaire !.
        '''</summary>
        Friend Shared ReadOnly Property _0167() As String
            Get
                Return ResourceManager.GetString("_0167", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à éléments.
        '''</summary>
        Friend Shared ReadOnly Property _0168() As String
            Get
                Return ResourceManager.GetString("_0168", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un répertoire.
        '''</summary>
        Friend Shared ReadOnly Property _0169() As String
            Get
                Return ResourceManager.GetString("_0169", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition de l&apos;item.
        '''</summary>
        Friend Shared ReadOnly Property _0170() As String
            Get
                Return ResourceManager.GetString("_0170", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible d&apos;afficher la galerie. La galerie n&apos;est pas assez large pour afficher les miniatures..
        '''</summary>
        Friend Shared ReadOnly Property _0171() As String
            Get
                Return ResourceManager.GetString("_0171", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible d&apos;afficher la galerie. La galerie n&apos;est pas assez haute pour afficher les miniatures..
        '''</summary>
        Friend Shared ReadOnly Property _0172() As String
            Get
                Return ResourceManager.GetString("_0172", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à L&apos;image au chemin d&apos;accès suivant est corrompu et ne pourra donc être affichée..
        '''</summary>
        Friend Shared ReadOnly Property _0173() As String
            Get
                Return ResourceManager.GetString("_0173", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un lien.
        '''</summary>
        Friend Shared ReadOnly Property _0174() As String
            Get
                Return ResourceManager.GetString("_0174", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un separateur.
        '''</summary>
        Friend Shared ReadOnly Property _0175() As String
            Get
                Return ResourceManager.GetString("_0175", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Zone de textes du lien.
        '''</summary>
        Friend Shared ReadOnly Property _0176() As String
            Get
                Return ResourceManager.GetString("_0176", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Zone de textes.
        '''</summary>
        Friend Shared ReadOnly Property _0177() As String
            Get
                Return ResourceManager.GetString("_0177", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter une ligne.
        '''</summary>
        Friend Shared ReadOnly Property _0178() As String
            Get
                Return ResourceManager.GetString("_0178", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter le plan du site.
        '''</summary>
        Friend Shared ReadOnly Property _0179() As String
            Get
                Return ResourceManager.GetString("_0179", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition.
        '''</summary>
        Friend Shared ReadOnly Property _0180() As String
            Get
                Return ResourceManager.GetString("_0180", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pas d&apos;élément {0} sur la page.
        '''</summary>
        Friend Shared ReadOnly Property _0181() As String
            Get
                Return ResourceManager.GetString("_0181", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Gestion des articles.
        '''</summary>
        Friend Shared ReadOnly Property _0183() As String
            Get
                Return ResourceManager.GetString("_0183", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition d&apos;un article.
        '''</summary>
        Friend Shared ReadOnly Property _0184() As String
            Get
                Return ResourceManager.GetString("_0184", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un article.
        '''</summary>
        Friend Shared ReadOnly Property _0185() As String
            Get
                Return ResourceManager.GetString("_0185", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un article externe.
        '''</summary>
        Friend Shared ReadOnly Property _0186() As String
            Get
                Return ResourceManager.GetString("_0186", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte.
        '''</summary>
        Friend Shared ReadOnly Property _0187() As String
            Get
                Return ResourceManager.GetString("_0187", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mot de passe.
        '''</summary>
        Friend Shared ReadOnly Property _0188() As String
            Get
                Return ResourceManager.GetString("_0188", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attention, toutes les informations ne sont pas remplies.
        '''Ces informations sont indispensables au fonctionnement d&apos;un flux RSS.
        '''Souhaitez-vous les completer?.
        '''</summary>
        Friend Shared ReadOnly Property _0189() As String
            Get
                Return ResourceManager.GetString("_0189", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible de charger le flux Rss..
        '''</summary>
        Friend Shared ReadOnly Property _0190() As String
            Get
                Return ResourceManager.GetString("_0190", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le flux Rss ne possède aucun article valide..
        '''</summary>
        Friend Shared ReadOnly Property _0191() As String
            Get
                Return ResourceManager.GetString("_0191", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Erreur impossible de télécharger l&apos;image.
        '''</summary>
        Friend Shared ReadOnly Property _0192() As String
            Get
                Return ResourceManager.GetString("_0192", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le Flux Rss n&apos;est pas disponible.
        '''</summary>
        Friend Shared ReadOnly Property _0193() As String
            Get
                Return ResourceManager.GetString("_0193", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Haut .
        '''</summary>
        Friend Shared ReadOnly Property _0194() As String
            Get
                Return ResourceManager.GetString("_0194", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bas.
        '''</summary>
        Friend Shared ReadOnly Property _0195() As String
            Get
                Return ResourceManager.GetString("_0195", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Gauche.
        '''</summary>
        Friend Shared ReadOnly Property _0196() As String
            Get
                Return ResourceManager.GetString("_0196", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Droite.
        '''</summary>
        Friend Shared ReadOnly Property _0197() As String
            Get
                Return ResourceManager.GetString("_0197", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le paquet a déjà été chargé .
        '''</summary>
        Friend Shared ReadOnly Property _0198() As String
            Get
                Return ResourceManager.GetString("_0198", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supprimer les éléments et les autres données liés au paquet?.
        '''</summary>
        Friend Shared ReadOnly Property _0199() As String
            Get
                Return ResourceManager.GetString("_0199", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Certaines images n&apos;étant pas proportionnel aux dimensions du carrousel, elles  seront  redimensionnées pour s&apos;afficher correctement..
        '''</summary>
        Friend Shared ReadOnly Property _0200() As String
            Get
                Return ResourceManager.GetString("_0200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Erreurs de proportionnalités.
        '''</summary>
        Friend Shared ReadOnly Property _0201() As String
            Get
                Return ResourceManager.GetString("_0201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suivre.
        '''</summary>
        Friend Shared ReadOnly Property _0202() As String
            Get
                Return ResourceManager.GetString("_0202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter des images.
        '''</summary>
        Friend Shared ReadOnly Property _0203() As String
            Get
                Return ResourceManager.GetString("_0203", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
