'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4984
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources.text
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizablePropertyNames
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebElement.LocalizablePropertyNames", GetType(LocalizablePropertyNames).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration.
        '''</summary>
        Friend Shared ReadOnly Property _N001() As String
            Get
                Return ResourceManager.GetString("_N001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image.
        '''</summary>
        Friend Shared ReadOnly Property _N002() As String
            Get
                Return ResourceManager.GetString("_N002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien.
        '''</summary>
        Friend Shared ReadOnly Property _N003() As String
            Get
                Return ResourceManager.GetString("_N003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte alternatif.
        '''</summary>
        Friend Shared ReadOnly Property _N004() As String
            Get
                Return ResourceManager.GetString("_N004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Epaisseur.
        '''</summary>
        Friend Shared ReadOnly Property _N005() As String
            Get
                Return ResourceManager.GetString("_N005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur.
        '''</summary>
        Friend Shared ReadOnly Property _N006() As String
            Get
                Return ResourceManager.GetString("_N006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte.
        '''</summary>
        Friend Shared ReadOnly Property _N007() As String
            Get
                Return ResourceManager.GetString("_N007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fenêtre.
        '''</summary>
        Friend Shared ReadOnly Property _N010() As String
            Get
                Return ResourceManager.GetString("_N010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Flèche.
        '''</summary>
        Friend Shared ReadOnly Property _N012() As String
            Get
                Return ResourceManager.GetString("_N012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position.
        '''</summary>
        Friend Shared ReadOnly Property _N013() As String
            Get
                Return ResourceManager.GetString("_N013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Décalage X.
        '''</summary>
        Friend Shared ReadOnly Property _N014() As String
            Get
                Return ResourceManager.GetString("_N014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Décalage Y.
        '''</summary>
        Friend Shared ReadOnly Property _N015() As String
            Get
                Return ResourceManager.GetString("_N015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse animation ouverture.
        '''</summary>
        Friend Shared ReadOnly Property _N016() As String
            Get
                Return ResourceManager.GetString("_N016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse animation fermeture.
        '''</summary>
        Friend Shared ReadOnly Property _N017() As String
            Get
                Return ResourceManager.GetString("_N017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai de fermeture.
        '''</summary>
        Friend Shared ReadOnly Property _N018() As String
            Get
                Return ResourceManager.GetString("_N018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à URL.
        '''</summary>
        Friend Shared ReadOnly Property _N019() As String
            Get
                Return ResourceManager.GetString("_N019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur claire.
        '''</summary>
        Friend Shared ReadOnly Property _N020() As String
            Get
                Return ResourceManager.GetString("_N020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur foncée.
        '''</summary>
        Friend Shared ReadOnly Property _N021() As String
            Get
                Return ResourceManager.GetString("_N021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bordure.
        '''</summary>
        Friend Shared ReadOnly Property _N022() As String
            Get
                Return ResourceManager.GetString("_N022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fichier.
        '''</summary>
        Friend Shared ReadOnly Property _N023() As String
            Get
                Return ResourceManager.GetString("_N023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage automatique.
        '''</summary>
        Friend Shared ReadOnly Property _N024() As String
            Get
                Return ResourceManager.GetString("_N024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage.
        '''</summary>
        Friend Shared ReadOnly Property _N025() As String
            Get
                Return ResourceManager.GetString("_N025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répétition.
        '''</summary>
        Friend Shared ReadOnly Property _N026() As String
            Get
                Return ResourceManager.GetString("_N026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Proportionnel.
        '''</summary>
        Friend Shared ReadOnly Property _N027() As String
            Get
                Return ResourceManager.GetString("_N027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur de fond.
        '''</summary>
        Friend Shared ReadOnly Property _N028() As String
            Get
                Return ResourceManager.GetString("_N028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Contrôles.
        '''</summary>
        Friend Shared ReadOnly Property _N030() As String
            Get
                Return ResourceManager.GetString("_N030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Menu.
        '''</summary>
        Friend Shared ReadOnly Property _N036() As String
            Get
                Return ResourceManager.GetString("_N036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Qualité.
        '''</summary>
        Friend Shared ReadOnly Property _N037() As String
            Get
                Return ResourceManager.GetString("_N037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Alignement général.
        '''</summary>
        Friend Shared ReadOnly Property _N038() As String
            Get
                Return ResourceManager.GetString("_N038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Alignement précis.
        '''</summary>
        Friend Shared ReadOnly Property _N039() As String
            Get
                Return ResourceManager.GetString("_N039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Transparence.
        '''</summary>
        Friend Shared ReadOnly Property _N040() As String
            Get
                Return ResourceManager.GetString("_N040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Echelle.
        '''</summary>
        Friend Shared ReadOnly Property _N042() As String
            Get
                Return ResourceManager.GetString("_N042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Désactiver.
        '''</summary>
        Friend Shared ReadOnly Property _N044() As String
            Get
                Return ResourceManager.GetString("_N044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position titre.
        '''</summary>
        Friend Shared ReadOnly Property _N045() As String
            Get
                Return ResourceManager.GetString("_N045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Extensions autorisées.
        '''</summary>
        Friend Shared ReadOnly Property _N046() As String
            Get
                Return ResourceManager.GetString("_N046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tailles autorisées.
        '''</summary>
        Friend Shared ReadOnly Property _N047() As String
            Get
                Return ResourceManager.GetString("_N047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Largeur.
        '''</summary>
        Friend Shared ReadOnly Property _N048() As String
            Get
                Return ResourceManager.GetString("_N048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image à gauche.
        '''</summary>
        Friend Shared ReadOnly Property _N049() As String
            Get
                Return ResourceManager.GetString("_N049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image alignement.
        '''</summary>
        Friend Shared ReadOnly Property _N050() As String
            Get
                Return ResourceManager.GetString("_N050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Règles de validation.
        '''</summary>
        Friend Shared ReadOnly Property _N051() As String
            Get
                Return ResourceManager.GetString("_N051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image d&apos;erreur.
        '''</summary>
        Friend Shared ReadOnly Property _N052() As String
            Get
                Return ResourceManager.GetString("_N052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur de saisie.
        '''</summary>
        Friend Shared ReadOnly Property _N054() As String
            Get
                Return ResourceManager.GetString("_N054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Longueur texte.
        '''</summary>
        Friend Shared ReadOnly Property _N056() As String
            Get
                Return ResourceManager.GetString("_N056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lecture seule.
        '''</summary>
        Friend Shared ReadOnly Property _N057() As String
            Get
                Return ResourceManager.GetString("_N057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ascenseur.
        '''</summary>
        Friend Shared ReadOnly Property _N061() As String
            Get
                Return ResourceManager.GetString("_N061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Colonnes.
        '''</summary>
        Friend Shared ReadOnly Property _N062() As String
            Get
                Return ResourceManager.GetString("_N062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lignes.
        '''</summary>
        Friend Shared ReadOnly Property _N063() As String
            Get
                Return ResourceManager.GetString("_N063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste de choix.
        '''</summary>
        Friend Shared ReadOnly Property _N065() As String
            Get
                Return ResourceManager.GetString("_N065", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste d&apos;éléments.
        '''</summary>
        Friend Shared ReadOnly Property _N069() As String
            Get
                Return ResourceManager.GetString("_N069", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choix multiples.
        '''</summary>
        Friend Shared ReadOnly Property _N070() As String
            Get
                Return ResourceManager.GetString("_N070", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Activé.
        '''</summary>
        Friend Shared ReadOnly Property _N071() As String
            Get
                Return ResourceManager.GetString("_N071", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du groupe.
        '''</summary>
        Friend Shared ReadOnly Property _N072() As String
            Get
                Return ResourceManager.GetString("_N072", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur.
        '''</summary>
        Friend Shared ReadOnly Property _N075() As String
            Get
                Return ResourceManager.GetString("_N075", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Case cochée.
        '''</summary>
        Friend Shared ReadOnly Property _N078() As String
            Get
                Return ResourceManager.GetString("_N078", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liaisons.
        '''</summary>
        Friend Shared ReadOnly Property _N079() As String
            Get
                Return ResourceManager.GetString("_N079", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration d&apos;envoi.
        '''</summary>
        Friend Shared ReadOnly Property _N080() As String
            Get
                Return ResourceManager.GetString("_N080", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affichage.
        '''</summary>
        Friend Shared ReadOnly Property _N082() As String
            Get
                Return ResourceManager.GetString("_N082", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai.
        '''</summary>
        Friend Shared ReadOnly Property _N083() As String
            Get
                Return ResourceManager.GetString("_N083", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de vignettes.
        '''</summary>
        Friend Shared ReadOnly Property _N084() As String
            Get
                Return ResourceManager.GetString("_N084", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de pages.
        '''</summary>
        Friend Shared ReadOnly Property _N085() As String
            Get
                Return ResourceManager.GetString("_N085", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image suivante.
        '''</summary>
        Friend Shared ReadOnly Property _N086() As String
            Get
                Return ResourceManager.GetString("_N086", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image précédente.
        '''</summary>
        Friend Shared ReadOnly Property _N087() As String
            Get
                Return ResourceManager.GetString("_N087", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Page suivante.
        '''</summary>
        Friend Shared ReadOnly Property _N088() As String
            Get
                Return ResourceManager.GetString("_N088", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Page précédente.
        '''</summary>
        Friend Shared ReadOnly Property _N089() As String
            Get
                Return ResourceManager.GetString("_N089", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage automatique.
        '''</summary>
        Friend Shared ReadOnly Property _N090() As String
            Get
                Return ResourceManager.GetString("_N090", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lecture.
        '''</summary>
        Friend Shared ReadOnly Property _N091() As String
            Get
                Return ResourceManager.GetString("_N091", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pause.
        '''</summary>
        Friend Shared ReadOnly Property _N092() As String
            Get
                Return ResourceManager.GetString("_N092", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Par défaut.
        '''</summary>
        Friend Shared ReadOnly Property _N093() As String
            Get
                Return ResourceManager.GetString("_N093", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bouton de lecture.
        '''</summary>
        Friend Shared ReadOnly Property _N094() As String
            Get
                Return ResourceManager.GetString("_N094", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bouton de navigation.
        '''</summary>
        Friend Shared ReadOnly Property _N095() As String
            Get
                Return ResourceManager.GetString("_N095", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répertoire de base.
        '''</summary>
        Friend Shared ReadOnly Property _N096() As String
            Get
                Return ResourceManager.GetString("_N096", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hauteur.
        '''</summary>
        Friend Shared ReadOnly Property _N098() As String
            Get
                Return ResourceManager.GetString("_N098", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte à afficher lors d&apos;un clic droit.
        '''</summary>
        Friend Shared ReadOnly Property _N099() As String
            Get
                Return ResourceManager.GetString("_N099", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ecart des sous-menus.
        '''</summary>
        Friend Shared ReadOnly Property _N101() As String
            Get
                Return ResourceManager.GetString("_N101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position de l&apos;en-tête.
        '''</summary>
        Friend Shared ReadOnly Property _N102() As String
            Get
                Return ResourceManager.GetString("_N102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre.
        '''</summary>
        Friend Shared ReadOnly Property _N103() As String
            Get
                Return ResourceManager.GetString("_N103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Icône fermé.
        '''</summary>
        Friend Shared ReadOnly Property _N104() As String
            Get
                Return ResourceManager.GetString("_N104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Icône ouvert.
        '''</summary>
        Friend Shared ReadOnly Property _N105() As String
            Get
                Return ResourceManager.GetString("_N105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Description.
        '''</summary>
        Friend Shared ReadOnly Property _N107() As String
            Get
                Return ResourceManager.GetString("_N107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Texte lien.
        '''</summary>
        Friend Shared ReadOnly Property _N108() As String
            Get
                Return ResourceManager.GetString("_N108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Disposition.
        '''</summary>
        Friend Shared ReadOnly Property _N112() As String
            Get
                Return ResourceManager.GetString("_N112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position titre.
        '''</summary>
        Friend Shared ReadOnly Property _N113() As String
            Get
                Return ResourceManager.GetString("_N113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Alignement.
        '''</summary>
        Friend Shared ReadOnly Property _N114() As String
            Get
                Return ResourceManager.GetString("_N114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bloc de code.
        '''</summary>
        Friend Shared ReadOnly Property _N115() As String
            Get
                Return ResourceManager.GetString("_N115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste d&apos;images.
        '''</summary>
        Friend Shared ReadOnly Property _N116() As String
            Get
                Return ResourceManager.GetString("_N116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sens.
        '''</summary>
        Friend Shared ReadOnly Property _N117() As String
            Get
                Return ResourceManager.GetString("_N117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Décalage.
        '''</summary>
        Friend Shared ReadOnly Property _N118() As String
            Get
                Return ResourceManager.GetString("_N118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai.
        '''</summary>
        Friend Shared ReadOnly Property _N119() As String
            Get
                Return ResourceManager.GetString("_N119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Automatique.
        '''</summary>
        Friend Shared ReadOnly Property _N120() As String
            Get
                Return ResourceManager.GetString("_N120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse.
        '''</summary>
        Friend Shared ReadOnly Property _N121() As String
            Get
                Return ResourceManager.GetString("_N121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition.
        '''</summary>
        Friend Shared ReadOnly Property _N122() As String
            Get
                Return ResourceManager.GetString("_N122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image normal.
        '''</summary>
        Friend Shared ReadOnly Property _N123() As String
            Get
                Return ResourceManager.GetString("_N123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image au survol.
        '''</summary>
        Friend Shared ReadOnly Property _N124() As String
            Get
                Return ResourceManager.GetString("_N124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image au clic.
        '''</summary>
        Friend Shared ReadOnly Property _N125() As String
            Get
                Return ResourceManager.GetString("_N125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Script javascript.
        '''</summary>
        Friend Shared ReadOnly Property _N126() As String
            Get
                Return ResourceManager.GetString("_N126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mode d&apos;affichage.
        '''</summary>
        Friend Shared ReadOnly Property _N127() As String
            Get
                Return ResourceManager.GetString("_N127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image d&apos;origine.
        '''</summary>
        Friend Shared ReadOnly Property _N128() As String
            Get
                Return ResourceManager.GetString("_N128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image de zoom.
        '''</summary>
        Friend Shared ReadOnly Property _N129() As String
            Get
                Return ResourceManager.GetString("_N129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre.
        '''</summary>
        Friend Shared ReadOnly Property _N130() As String
            Get
                Return ResourceManager.GetString("_N130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Description.
        '''</summary>
        Friend Shared ReadOnly Property _N131() As String
            Get
                Return ResourceManager.GetString("_N131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Adresse URL.
        '''</summary>
        Friend Shared ReadOnly Property _N132() As String
            Get
                Return ResourceManager.GetString("_N132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Evénement.
        '''</summary>
        Friend Shared ReadOnly Property _N133() As String
            Get
                Return ResourceManager.GetString("_N133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille automatique.
        '''</summary>
        Friend Shared ReadOnly Property _N134() As String
            Get
                Return ResourceManager.GetString("_N134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Durée d&apos;ouverture.
        '''</summary>
        Friend Shared ReadOnly Property _N135() As String
            Get
                Return ResourceManager.GetString("_N135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur de fond des images.
        '''</summary>
        Friend Shared ReadOnly Property _N136() As String
            Get
                Return ResourceManager.GetString("_N136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration barre partage.
        '''</summary>
        Friend Shared ReadOnly Property _N137() As String
            Get
                Return ResourceManager.GetString("_N137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effet d&apos;animation.
        '''</summary>
        Friend Shared ReadOnly Property _N138() As String
            Get
                Return ResourceManager.GetString("_N138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration.
        '''</summary>
        Friend Shared ReadOnly Property _N139() As String
            Get
                Return ResourceManager.GetString("_N139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fermé.
        '''</summary>
        Friend Shared ReadOnly Property _N140() As String
            Get
                Return ResourceManager.GetString("_N140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Unique.
        '''</summary>
        Friend Shared ReadOnly Property _N141() As String
            Get
                Return ResourceManager.GetString("_N141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre.
        '''</summary>
        Friend Shared ReadOnly Property _N142() As String
            Get
                Return ResourceManager.GetString("_N142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien.
        '''</summary>
        Friend Shared ReadOnly Property _N143() As String
            Get
                Return ResourceManager.GetString("_N143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Icône.
        '''</summary>
        Friend Shared ReadOnly Property _N144() As String
            Get
                Return ResourceManager.GetString("_N144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fond transparent.
        '''</summary>
        Friend Shared ReadOnly Property _N145() As String
            Get
                Return ResourceManager.GetString("_N145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ouvert.
        '''</summary>
        Friend Shared ReadOnly Property _N146() As String
            Get
                Return ResourceManager.GetString("_N146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fermé.
        '''</summary>
        Friend Shared ReadOnly Property _N147() As String
            Get
                Return ResourceManager.GetString("_N147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration.
        '''</summary>
        Friend Shared ReadOnly Property _N148() As String
            Get
                Return ResourceManager.GetString("_N148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien sur la première image.
        '''</summary>
        Friend Shared ReadOnly Property _N149() As String
            Get
                Return ResourceManager.GetString("_N149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Première image.
        '''</summary>
        Friend Shared ReadOnly Property _N150() As String
            Get
                Return ResourceManager.GetString("_N150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Image du séparateur.
        '''</summary>
        Friend Shared ReadOnly Property _N151() As String
            Get
                Return ResourceManager.GetString("_N151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration avancée.
        '''</summary>
        Friend Shared ReadOnly Property _N152() As String
            Get
                Return ResourceManager.GetString("_N152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration.
        '''</summary>
        Friend Shared ReadOnly Property _N153() As String
            Get
                Return ResourceManager.GetString("_N153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Balise titre.
        '''</summary>
        Friend Shared ReadOnly Property _N154() As String
            Get
                Return ResourceManager.GetString("_N154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Largeur du cryptogramme.
        '''</summary>
        Friend Shared ReadOnly Property _N155() As String
            Get
                Return ResourceManager.GetString("_N155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hauteur du cryptogramme.
        '''</summary>
        Friend Shared ReadOnly Property _N156() As String
            Get
                Return ResourceManager.GetString("_N156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Temps du rechargement.
        '''</summary>
        Friend Shared ReadOnly Property _N157() As String
            Get
                Return ResourceManager.GetString("_N157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre maximum d&apos;essai.
        '''</summary>
        Friend Shared ReadOnly Property _N158() As String
            Get
                Return ResourceManager.GetString("_N158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N159() As String
            Get
                Return ResourceManager.GetString("_N159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleurs aléatoires.
        '''</summary>
        Friend Shared ReadOnly Property _N160() As String
            Get
                Return ResourceManager.GetString("_N160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Clarté des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N161() As String
            Get
                Return ResourceManager.GetString("_N161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Transparence des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N162() As String
            Get
                Return ResourceManager.GetString("_N162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Police des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N163() As String
            Get
                Return ResourceManager.GetString("_N163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Majuscules/minuscules.
        '''</summary>
        Friend Shared ReadOnly Property _N164() As String
            Get
                Return ResourceManager.GetString("_N164", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre minimum de caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N165() As String
            Get
                Return ResourceManager.GetString("_N165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre maximum de caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N166() As String
            Get
                Return ResourceManager.GetString("_N166", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Espace inter caractères .
        '''</summary>
        Friend Shared ReadOnly Property _N167() As String
            Get
                Return ResourceManager.GetString("_N167", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille minimum des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N168() As String
            Get
                Return ResourceManager.GetString("_N168", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille maximum des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N169() As String
            Get
                Return ResourceManager.GetString("_N169", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Angle maximum des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N170() As String
            Get
                Return ResourceManager.GetString("_N170", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Déplacement vertical des caractères.
        '''</summary>
        Friend Shared ReadOnly Property _N171() As String
            Get
                Return ResourceManager.GetString("_N171", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pixels minimum.
        '''</summary>
        Friend Shared ReadOnly Property _N172() As String
            Get
                Return ResourceManager.GetString("_N172", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pixels maximum.
        '''</summary>
        Friend Shared ReadOnly Property _N173() As String
            Get
                Return ResourceManager.GetString("_N173", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lignes minimum.
        '''</summary>
        Friend Shared ReadOnly Property _N174() As String
            Get
                Return ResourceManager.GetString("_N174", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lignes maximum.
        '''</summary>
        Friend Shared ReadOnly Property _N175() As String
            Get
                Return ResourceManager.GetString("_N175", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cercles minimum.
        '''</summary>
        Friend Shared ReadOnly Property _N176() As String
            Get
                Return ResourceManager.GetString("_N176", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cercles maximum.
        '''</summary>
        Friend Shared ReadOnly Property _N177() As String
            Get
                Return ResourceManager.GetString("_N177", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Couleur .
        '''</summary>
        Friend Shared ReadOnly Property _N178() As String
            Get
                Return ResourceManager.GetString("_N178", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Taille .
        '''</summary>
        Friend Shared ReadOnly Property _N179() As String
            Get
                Return ResourceManager.GetString("_N179", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Au-dessus.
        '''</summary>
        Friend Shared ReadOnly Property _N180() As String
            Get
                Return ResourceManager.GetString("_N180", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Autorisé.
        '''</summary>
        Friend Shared ReadOnly Property _N181() As String
            Get
                Return ResourceManager.GetString("_N181", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Message d&apos;erreur.
        '''</summary>
        Friend Shared ReadOnly Property _N182() As String
            Get
                Return ResourceManager.GetString("_N182", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à URLs vidéo.
        '''</summary>
        Friend Shared ReadOnly Property _N183() As String
            Get
                Return ResourceManager.GetString("_N183", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Affiche.
        '''</summary>
        Friend Shared ReadOnly Property _N184() As String
            Get
                Return ResourceManager.GetString("_N184", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Contrôles par défaut.
        '''</summary>
        Friend Shared ReadOnly Property _N185() As String
            Get
                Return ResourceManager.GetString("_N185", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Contrôles personnalisés.
        '''</summary>
        Friend Shared ReadOnly Property _N186() As String
            Get
                Return ResourceManager.GetString("_N186", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lecture automatique.
        '''</summary>
        Friend Shared ReadOnly Property _N187() As String
            Get
                Return ResourceManager.GetString("_N187", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Répétition.
        '''</summary>
        Friend Shared ReadOnly Property _N188() As String
            Get
                Return ResourceManager.GetString("_N188", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Muet.
        '''</summary>
        Friend Shared ReadOnly Property _N189() As String
            Get
                Return ResourceManager.GetString("_N189", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Message Echec Plugins.
        '''</summary>
        Friend Shared ReadOnly Property _N190() As String
            Get
                Return ResourceManager.GetString("_N190", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Barres de défilement.
        '''</summary>
        Friend Shared ReadOnly Property _N191() As String
            Get
                Return ResourceManager.GetString("_N191", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bordures.
        '''</summary>
        Friend Shared ReadOnly Property _N192() As String
            Get
                Return ResourceManager.GetString("_N192", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Script.
        '''</summary>
        Friend Shared ReadOnly Property _N193() As String
            Get
                Return ResourceManager.GetString("_N193", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property _N194() As String
            Get
                Return ResourceManager.GetString("_N194", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property _N195() As String
            Get
                Return ResourceManager.GetString("_N195", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Valeur.
        '''</summary>
        Friend Shared ReadOnly Property _N196() As String
            Get
                Return ResourceManager.GetString("_N196", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de colonne.
        '''</summary>
        Friend Shared ReadOnly Property _N197() As String
            Get
                Return ResourceManager.GetString("_N197", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de ligne.
        '''</summary>
        Friend Shared ReadOnly Property _N198() As String
            Get
                Return ResourceManager.GetString("_N198", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Indicateurs.
        '''</summary>
        Friend Shared ReadOnly Property _N199() As String
            Get
                Return ResourceManager.GetString("_N199", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Edition verrouillée.
        '''</summary>
        Friend Shared ReadOnly Property _N201() As String
            Get
                Return ResourceManager.GetString("_N201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre.
        '''</summary>
        Friend Shared ReadOnly Property _N202() As String
            Get
                Return ResourceManager.GetString("_N202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Date.
        '''</summary>
        Friend Shared ReadOnly Property _N203() As String
            Get
                Return ResourceManager.GetString("_N203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Description.
        '''</summary>
        Friend Shared ReadOnly Property _N204() As String
            Get
                Return ResourceManager.GetString("_N204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lien.
        '''</summary>
        Friend Shared ReadOnly Property _N205() As String
            Get
                Return ResourceManager.GetString("_N205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Gestion Article.
        '''</summary>
        Friend Shared ReadOnly Property _N206() As String
            Get
                Return ResourceManager.GetString("_N206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Article Existant.
        '''</summary>
        Friend Shared ReadOnly Property _N207() As String
            Get
                Return ResourceManager.GetString("_N207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attribut name.
        '''</summary>
        Friend Shared ReadOnly Property _N208() As String
            Get
                Return ResourceManager.GetString("_N208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Selectionné.
        '''</summary>
        Friend Shared ReadOnly Property _N209() As String
            Get
                Return ResourceManager.GetString("_N209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Type.
        '''</summary>
        Friend Shared ReadOnly Property _N210() As String
            Get
                Return ResourceManager.GetString("_N210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Auto complete.
        '''</summary>
        Friend Shared ReadOnly Property _N211() As String
            Get
                Return ResourceManager.GetString("_N211", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Multiple.
        '''</summary>
        Friend Shared ReadOnly Property _N212() As String
            Get
                Return ResourceManager.GetString("_N212", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler le redimensionnement.
        '''</summary>
        Friend Shared ReadOnly Property _N213() As String
            Get
                Return ResourceManager.GetString("_N213", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position de départ.
        '''</summary>
        Friend Shared ReadOnly Property _N214() As String
            Get
                Return ResourceManager.GetString("_N214", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ouvert.
        '''</summary>
        Friend Shared ReadOnly Property _N215() As String
            Get
                Return ResourceManager.GetString("_N215", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Entête du flux Rss.
        '''</summary>
        Friend Shared ReadOnly Property _N216() As String
            Get
                Return ResourceManager.GetString("_N216", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste des articles du flux.
        '''</summary>
        Friend Shared ReadOnly Property _N217() As String
            Get
                Return ResourceManager.GetString("_N217", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Liste des pages.
        '''</summary>
        Friend Shared ReadOnly Property _N218() As String
            Get
                Return ResourceManager.GetString("_N218", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Element précèdent.
        '''</summary>
        Friend Shared ReadOnly Property _N219() As String
            Get
                Return ResourceManager.GetString("_N219", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Element suivant.
        '''</summary>
        Friend Shared ReadOnly Property _N220() As String
            Get
                Return ResourceManager.GetString("_N220", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Direction.
        '''</summary>
        Friend Shared ReadOnly Property _N221() As String
            Get
                Return ResourceManager.GetString("_N221", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai.
        '''</summary>
        Friend Shared ReadOnly Property _N222() As String
            Get
                Return ResourceManager.GetString("_N222", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Accès direct.
        '''</summary>
        Friend Shared ReadOnly Property _N223() As String
            Get
                Return ResourceManager.GetString("_N223", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Précèdent.
        '''</summary>
        Friend Shared ReadOnly Property _N224() As String
            Get
                Return ResourceManager.GetString("_N224", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Suivant.
        '''</summary>
        Friend Shared ReadOnly Property _N225() As String
            Get
                Return ResourceManager.GetString("_N225", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage automatique.
        '''</summary>
        Friend Shared ReadOnly Property _N226() As String
            Get
                Return ResourceManager.GetString("_N226", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Survol actif.
        '''</summary>
        Friend Shared ReadOnly Property _N227() As String
            Get
                Return ResourceManager.GetString("_N227", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai de démarrage.
        '''</summary>
        Friend Shared ReadOnly Property _N228() As String
            Get
                Return ResourceManager.GetString("_N228", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lecture.
        '''</summary>
        Friend Shared ReadOnly Property _N229() As String
            Get
                Return ResourceManager.GetString("_N229", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Stop.
        '''</summary>
        Friend Shared ReadOnly Property _N230() As String
            Get
                Return ResourceManager.GetString("_N230", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Infini.
        '''</summary>
        Friend Shared ReadOnly Property _N231() As String
            Get
                Return ResourceManager.GetString("_N231", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effet.
        '''</summary>
        Friend Shared ReadOnly Property _N232() As String
            Get
                Return ResourceManager.GetString("_N232", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Espace inter-pages.
        '''</summary>
        Friend Shared ReadOnly Property _N233() As String
            Get
                Return ResourceManager.GetString("_N233", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mode d&apos;affichage.
        '''</summary>
        Friend Shared ReadOnly Property _N234() As String
            Get
                Return ResourceManager.GetString("_N234", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effet d&apos;ouverture.
        '''</summary>
        Friend Shared ReadOnly Property _N235() As String
            Get
                Return ResourceManager.GetString("_N235", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Effet de fermeture.
        '''</summary>
        Friend Shared ReadOnly Property _N236() As String
            Get
                Return ResourceManager.GetString("_N236", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration des drapeaux.
        '''</summary>
        Friend Shared ReadOnly Property _N237() As String
            Get
                Return ResourceManager.GetString("_N237", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Source.
        '''</summary>
        Friend Shared ReadOnly Property _N238() As String
            Get
                Return ResourceManager.GetString("_N238", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sélectionner les éléments.
        '''</summary>
        Friend Shared ReadOnly Property _N239() As String
            Get
                Return ResourceManager.GetString("_N239", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attribuer les sources (valeurs).
        '''</summary>
        Friend Shared ReadOnly Property _N240() As String
            Get
                Return ResourceManager.GetString("_N240", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Garder les paramètres URL actuels.
        '''</summary>
        Friend Shared ReadOnly Property _N241() As String
            Get
                Return ResourceManager.GetString("_N241", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai d&apos;ouverture.
        '''</summary>
        Friend Shared ReadOnly Property _N242() As String
            Get
                Return ResourceManager.GetString("_N242", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Délai de fermeture.
        '''</summary>
        Friend Shared ReadOnly Property _N243() As String
            Get
                Return ResourceManager.GetString("_N243", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Activer la liste dynamique.
        '''</summary>
        Friend Shared ReadOnly Property _N244() As String
            Get
                Return ResourceManager.GetString("_N244", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
